instaspin_motion: PROJ_LAB06d
PROJ_LAB06d
Modules
Project Overview
Macros
#define LED_BLINK_FREQ_Hz 5
#define ST_VELPLAN_CFG_ARRAY_DWORDS
Enumerations
enum PLAN_SELECT_e { TEST_PATTERN =0, GROCERY_CONVEYOR, GARAGE_DOOR }
enum TEST_State_e {
TEST_0 = 0, TEST_4000, TEST_N4000, TEST_2000,
TEST_N2000, TEST_1000, TEST_N1000, TEST_500,
TEST_N500, TEST_250, TEST_N250, NUM_TEST_STATES
}
enum TEST_Trans_e {
TEST_0to4000 = 0, TEST_4000toN4000, TEST_N4000to2000, TEST_2000toN2000,
TEST_N2000to1000, TEST_1000toN1000, TEST_N1000to500, TEST_500toN500,
TEST_N500to250, TEST_250toN250, TEST_N250to0, NUM_TEST_TRANS
}
enum GROCERY_State_e { GROCERY_Idle = 0, GROCERY_Convey, NUM_GROCERY_STATES }
enum GROCERY_Vars_e { GROCERY_OnOff = 0, GROCERY_ProxSensor, NUM_GROCERY_VARS }
enum GROCERY_Cond_e {
GROCERY_SwitchOn = 0, GROCERY_SwitchOff, GROCERY_ProxOpen, GROCERY_ProxBlocked,
NUM_GROCERY_CONDS
}
enum GROCERY_Trans_e { GROCERY_IdleToConvey = 0, GROCERY_ConveyToIdle, NUM_GROCERY_TRANS }
enum GARAGE_State_e { GARAGE_Idle = 0, GARAGE_Down, GARAGE_Up, NUM_GARAGE_STATES }
enum GARAGE_Vars_e { GARAGE_DownSensor = 0, GARAGE_UpSensor, GARAGE_Button, NUM_GARAGE_VARS }
enum GARAGE_Cond_e { GARAGE_DoorDown = 0, GARAGE_DoorUp, GARAGE_ButtonPressed, NUM_GARAGE_CONDS }
enum GARAGE_Acts_e {
GARAGE_ClearButtonDown = 0, GARAGE_ClearButtonUp, GARAGE_ClearDownSensor, GARAGE_ClearUpSensor,
NUM_GARAGE_ACTS
}
enum GARAGE_Trans_e {
GARAGE_IdleToDown = 0, GARAGE_IdleToUp, GARAGE_DownToUp, GARAGE_UpToDown,
GARAGE_DownToIdle, GARAGE_UpToIdle, NUM_GARAGE_TRANS
}
Functions
void ST_setupVelPlan_TestPattern (ST_Handle sthandle)
void ST_setupVelPlan_GroceryConveyor (ST_Handle sthandle)
void ST_setupVelPlan_GarageDoor (ST_Handle sthandle)
void main (void)
interrupt void mainISR (void)
The main interrupt service (ISR) routine.
void updateGlobalVariables_motor (CTRL_Handle handle, ST_Handle sthandle)
Updates the global motor variables.
void updateKpKiGains (CTRL_Handle handle)
Updates Kp and Ki gains in the controller object.
void ST_setupVelPlan (ST_Handle handle)
Setups SpinTAC Velocity Plan.
void ST_runVelPlan (ST_Handle handle, CTRL_Handle ctrlHandle)
Runs SpinTAC Velocity Plan.
void ST_runVelMove (ST_Handle handle, CTRL_Handle ctrlHandle)
Runs SpinTAC Velocity Move.
void ST_runVelCtl (ST_Handle handle, CTRL_Handle ctrlHandle)
Runs SpinTAC Velocity Control.
Variables
uint_least16_t gCounter_updateGlobals = 0
bool Flag_Latch_softwareUpdate = true
CTRL_Handle ctrlHandle
HAL_Handle halHandle
USER_Params gUserParams
HAL_PwmData_t gPwmData = {_IQ(0.0), _IQ(0.0), _IQ(0.0)}
HAL_AdcData_t gAdcData
_iq gMaxCurrentSlope = _IQ(0.0)
CTRL_Obj ctrl
ST_Obj st_obj
ST_Handle stHandle
ST_PlanButton_e gVelPlanRunFlag = ST_PLAN_STOP
PLAN_SELECT_e gSelectedPlan = TEST_PATTERN
PLAN_SELECT_e gConfiguredPlan = TEST_PATTERN
uint32_t stVelPlanCfgArray [ST_VELPLAN_CFG_ARRAY_DWORDS]
TEST_State_e gTestState = TEST_0
GROCERY_State_e gGroceryState = GROCERY_Idle
_iq gGroceryConveyorOnOff = 0
_iq gGroceryConveyorProxSensor = 0
GARAGE_State_e gGarageState = GARAGE_Idle
_iq gGarageDoorDown = 1
_iq gGarageDoorUp = 0
_iq gGarageDoorButton = 0
uint16_t gLEDcnt = 0
volatile MOTOR_Vars_t gMotorVars = MOTOR_Vars_INIT
_iq gFlux_pu_to_Wb_sf
_iq gFlux_pu_to_VpHz_sf
_iq gTorque_Ls_Id_Iq_pu_to_Nm_sf
_iq gTorque_Flux_Iq_pu_to_Nm_sf
Detailed Description
Macro Definition Documentation
#define LED_BLINK_FREQ_Hz 5
Definition at line 65 of file proj_lab06d.c.
Referenced by mainISR().
#define ST_VELPLAN_CFG_ARRAY_DWORDS
Value:
((ST_VEL_PLAN_ACT_DWORDS     * 5)  + \
                                        (ST_VEL_PLAN_COND_DWORDS    * 5) + \
                                        (ST_VEL_PLAN_VAR_DWORDS     * 5)  + \
                                        (ST_VEL_PLAN_TRAN_DWORDS    * 15) + \
                                        (ST_VEL_PLAN_STATE_DWORDS   * 15))
Definition at line 233 of file proj_lab06d.c.
Enumeration Type Documentation
enum GARAGE_Acts_e
Enumerator
GARAGE_ClearButtonDown
GARAGE_ClearButtonUp
GARAGE_ClearDownSensor
GARAGE_ClearUpSensor
NUM_GARAGE_ACTS
Definition at line 211 of file proj_lab06d.c.
enum GARAGE_Cond_e
Enumerator
GARAGE_DoorDown
GARAGE_DoorUp
GARAGE_ButtonPressed
NUM_GARAGE_CONDS
Definition at line 202 of file proj_lab06d.c.
enum GARAGE_State_e
Enumerator
GARAGE_Idle
GARAGE_Down
GARAGE_Up
NUM_GARAGE_STATES
Definition at line 184 of file proj_lab06d.c.
enum GARAGE_Trans_e
Enumerator
GARAGE_IdleToDown
GARAGE_IdleToUp
GARAGE_DownToUp
GARAGE_UpToDown
GARAGE_DownToIdle
GARAGE_UpToIdle
NUM_GARAGE_TRANS
Definition at line 221 of file proj_lab06d.c.
enum GARAGE_Vars_e
Enumerator
GARAGE_DownSensor
GARAGE_UpSensor
GARAGE_Button
NUM_GARAGE_VARS
Definition at line 193 of file proj_lab06d.c.
enum GROCERY_Cond_e
Enumerator
GROCERY_SwitchOn
GROCERY_SwitchOff
GROCERY_ProxOpen
GROCERY_ProxBlocked
NUM_GROCERY_CONDS
Definition at line 165 of file proj_lab06d.c.
enum GROCERY_State_e
Enumerator
GROCERY_Idle
GROCERY_Convey
NUM_GROCERY_STATES
Definition at line 149 of file proj_lab06d.c.
enum GROCERY_Trans_e
Enumerator
GROCERY_IdleToConvey
GROCERY_ConveyToIdle
NUM_GROCERY_TRANS
Definition at line 175 of file proj_lab06d.c.
enum GROCERY_Vars_e
Enumerator
GROCERY_OnOff
GROCERY_ProxSensor
NUM_GROCERY_VARS
Definition at line 157 of file proj_lab06d.c.
enum PLAN_SELECT_e
Enumerator
TEST_PATTERN
GROCERY_CONVEYOR
GARAGE_DOOR
Definition at line 68 of file proj_lab06d.c.
enum TEST_State_e
Enumerator
TEST_0
TEST_4000
TEST_N4000
TEST_2000
TEST_N2000
TEST_1000
TEST_N1000
TEST_500
TEST_N500
TEST_250
TEST_N250
NUM_TEST_STATES
Definition at line 114 of file proj_lab06d.c.
enum TEST_Trans_e
Enumerator
TEST_0to4000
TEST_4000toN4000
TEST_N4000to2000
TEST_2000toN2000
TEST_N2000to1000
TEST_1000toN1000
TEST_N1000to500
TEST_500toN500
TEST_N500to250
TEST_250toN250
TEST_N250to0
NUM_TEST_TRANS
Definition at line 131 of file proj_lab06d.c.
Function Documentation
void main (void)
Definition at line 286 of file proj_lab06d.c.
References _IQ, _IQmpy, CTRL_getFlag_enableUserMotorParams(), CTRL_getKi(), CTRL_getKp(), CTRL_getState(), CTRL_getVersion(), CTRL_initCtrl(), CTRL_isError(), CTRL_setFlag_enableCtrl(), CTRL_setFlag_enableDcBusComp(), CTRL_setFlag_enableOffset(), CTRL_setFlag_enablePowerWarp(), CTRL_setFlag_enableSpeedCtrl(), CTRL_setFlag_enableUserMotorParams(), CTRL_setMaxAccel_pu(), CTRL_setParams(), CTRL_setSpd_ref_krpm(), CTRL_updateState(), _MOTOR_Vars_t_::CtrlVersion, EST_getMaxCurrentSlope_pu(), EST_getState(), EST_isMotorIdentified(), EST_setFlag_enableForceAngle(), EST_setFlag_enableRsRecalc(), EST_setMaxCurrentSlope_pu(), _CTRL_Obj_::estHandle, _MOTOR_Vars_t_::Flag_enableForceAngle, _MOTOR_Vars_t_::Flag_enableOffsetcalc, _MOTOR_Vars_t_::Flag_enablePowerWarp, _MOTOR_Vars_t_::Flag_enableRsRecalc, _MOTOR_Vars_t_::Flag_enableSys, _MOTOR_Vars_t_::Flag_enableUserParams, Flag_Latch_softwareUpdate, _MOTOR_Vars_t_::Flag_MotorIdentified, _MOTOR_Vars_t_::Flag_Run_Identify, GARAGE_DOOR, gConfiguredPlan, gCounter_updateGlobals, gFlux_pu_to_VpHz_sf, gFlux_pu_to_Wb_sf, gMaxCurrentSlope, GROCERY_CONVEYOR, gSelectedPlan, gTorque_Flux_Iq_pu_to_Nm_sf, gTorque_Ls_Id_Iq_pu_to_Nm_sf, hal, HAL_disablePwm(), HAL_enableAdcInts(), HAL_enableDebugInt(), HAL_enableGlobalInts(), HAL_enablePwm(), HAL_getBias(), HAL_init(), HAL_initIntVectorTable(), HAL_setBias(), HAL_setParams(), HAL_setupFaults(), HAL_updateAdcBias(), I_A_offset, I_B_offset, _MOTOR_Vars_t_::I_bias, I_C_offset, _MOTOR_Vars_t_::Ki_Idq, _MOTOR_Vars_t_::Kp_Idq, MAX_ACCEL_KRPMPS_SF, _MOTOR_Vars_t_::MaxAccel_krpmps, memCopy(), _CTRL_Version_::minor, NUM_MAIN_TICKS_FOR_GLOBAL_VARIABLE_UPDATE, _MOTOR_Vars_t_::SpeedRef_krpm, _MOTOR_Vars_t_::SpinTAC, ST_init(), ST_runVelPlan(), ST_setupVelCtl(), ST_setupVelMove(), ST_setupVelPlan(), ST_setupVelPlan_GarageDoor(), ST_setupVelPlan_GroceryConveyor(), ST_setupVelPlan_TestPattern(), stHandle, STVELCTL_getBandwidth_radps(), STVELCTL_getOutputMaximum(), STVELCTL_getOutputMinimum(), STVELCTL_setBandwidth_radps(), STVELCTL_setEnable(), STVELCTL_setOutputMaximums(), STVELMOVE_setVelocityEnd(), STVELMOVE_setVelocityStart(), STVELPLAN_getStatus(), TEST_PATTERN, updateGlobalVariables_motor(), updateKpKiGains(), USER_calcPIgains(), USER_checkForErrors(), USER_computeFlux_pu_to_VpHz_sf(), USER_computeFlux_pu_to_Wb_sf(), USER_computeTorque_Flux_Iq_pu_to_Nm_sf(), USER_computeTorque_Ls_Id_Iq_pu_to_Nm_sf(), USER_getErrorCode(), USER_IQ_FULL_SCALE_CURRENT_A, USER_setParams(), USER_softwareUpdate1p6(), _MOTOR_Vars_t_::UserErrorCode, V_A_offset, V_B_offset, _MOTOR_Vars_t_::V_bias, V_C_offset, _MATH_vec3_::value, _ST_Vars_t::VelCtlBw_radps, _ST_Obj::velCtlHandle, _ST_Vars_t::VelCtlOutputMax_A, _ST_Vars_t::VelCtlOutputMin_A, _ST_Obj::velMoveHandle, and _ST_Obj::velPlanHandle.
interrupt void mainISR (void)
The main interrupt service (ISR) routine.
Definition at line 670 of file proj_lab06d.c.
References CTRL_run(), CTRL_setup(), gLEDcnt, HAL_acqAdcInt(), HAL_readAdcData(), HAL_toggleLed, HAL_writePwmData(), ISR_TICKS_PER_SPINTAC_TICK, LED_BLINK_FREQ_Hz, ST_runVelCtl(), ST_runVelMove(), ST_runVelPlanTick(), stHandle, and USER_ISR_FREQ_Hz.
void ST_runVelCtl (ST_Handle handle, CTRL_Handle ctrlHandle)
Runs SpinTAC Velocity Control.
Definition at line 1083 of file proj_lab06d.c.
References CTRL_setIq_ref_pu(), EST_getFm_pu(), _CTRL_Obj_::estHandle, STVELCTL_getTorqueReference(), STVELCTL_run(), STVELCTL_setAccelerationReference(), STVELCTL_setVelocityFeedback(), STVELCTL_setVelocityReference(), STVELMOVE_getAccelerationReference(), STVELMOVE_getVelocityReference(), _ST_Obj::velCtlHandle, and _ST_Obj::velMoveHandle.
Referenced by mainISR().
void ST_runVelMove (ST_Handle handle, CTRL_Handle ctrlHandle)
Runs SpinTAC Velocity Move.
Definition at line 1053 of file proj_lab06d.c.
References _IQ, _IQ20, _IQ20mpy, _IQabs, _IQmpy, EST_getState(), EST_setFlag_enableForceAngle(), _CTRL_Obj_::estHandle, _MOTOR_Vars_t_::Flag_enableForceAngle, _MOTOR_Vars_t_::MaxAccel_krpmps, _MOTOR_Vars_t_::MaxJrk_krpmps2, _MOTOR_Vars_t_::SpeedRef_krpm, _MOTOR_Vars_t_::SpinTAC, ST_MIN_ID_SPEED_PU, ST_SPEED_PU_PER_KRPM, STVELMOVE_getVelocityEnd(), STVELMOVE_getVelocityStart(), STVELMOVE_run(), STVELMOVE_setAccelerationLimit(), STVELMOVE_setCurveType(), STVELMOVE_setEnable(), STVELMOVE_setJerkLimit(), STVELMOVE_setVelocityEnd(), _ST_Vars_t::VelMoveCurveType, and _ST_Obj::velMoveHandle.
Referenced by mainISR().
void ST_runVelPlan (ST_Handle handle, CTRL_Handle ctrlHandle)
Runs SpinTAC Velocity Plan.
Definition at line 960 of file proj_lab06d.c.
References _IQ, _IQ20, _IQ20mpy, _IQabs, _IQmpy, EST_getFm_pu(), _CTRL_Obj_::estHandle, GARAGE_DOOR, gConfiguredPlan, gGarageDoorButton, gGarageDoorDown, gGarageDoorUp, gGarageState, gGroceryConveyorOnOff, gGroceryConveyorProxSensor, gGroceryState, GROCERY_CONVEYOR, gSelectedPlan, gState, gTestState, gVelPlanRunFlag, _MOTOR_Vars_t_::MaxAccel_krpmps, _MOTOR_Vars_t_::MaxJrk_krpmps2, _MOTOR_Vars_t_::SpeedRef_krpm, _MOTOR_Vars_t_::SpinTAC, ST_MIN_ID_SPEED_PU, ST_PLAN_PAUSE, ST_PLAN_START, ST_PLAN_STOP, ST_SPEED_KRPM_PER_PU, _MOTOR_Vars_t_::StopSpeedRef_krpm, STVELPLAN_getAccelerationLimit(), STVELPLAN_getCurrentState(), STVELPLAN_getErrorID(), STVELPLAN_getFsmState(), STVELPLAN_getJerkLimit(), STVELPLAN_getStatus(), STVELPLAN_getVar(), STVELPLAN_getVelocitySetpoint(), STVELPLAN_run(), STVELPLAN_setEnable(), STVELPLAN_setReset(), STVELPLAN_setVar(), TEST_PATTERN, _ST_Obj::velPlanHandle, and _ST_Vars_t::VelPlanRun.
Referenced by main().
void ST_setupVelPlan (ST_Handle handle)
Setups SpinTAC Velocity Plan.
Definition at line 817 of file proj_lab06d.c.
References _IQ, _IQ20, _IQ24, NUM_PLAN_STATES, NUM_PLAN_TRANS, ST_SAMPLE_TIME, ST_SPEED_PU_PER_KRPM, STATE_A, STATE_B, STATE_C, STVELPLAN_addCfgState(), STVELPLAN_addCfgTran(), STVELPLAN_setCfg(), STVELPLAN_setCfgArray(), STVELPLAN_setCfgHaltState(), stVelPlanCfgArray, and _ST_Obj::velPlanHandle.
Referenced by main().
void ST_setupVelPlan_GarageDoor (ST_Handle sthandle)
Definition at line 910 of file proj_lab06d.c.
References _IQ, _IQ20, _IQ24, GARAGE_Button, GARAGE_ButtonPressed, GARAGE_DoorDown, GARAGE_DoorUp, GARAGE_Down, GARAGE_DownSensor, GARAGE_Idle, GARAGE_Up, GARAGE_UpSensor, ST_SAMPLE_TIME, ST_SPEED_PU_PER_KRPM, STVELPLAN_addCfgAct(), STVELPLAN_addCfgCond(), STVELPLAN_addCfgState(), STVELPLAN_addCfgTran(), STVELPLAN_addCfgVar(), STVELPLAN_reset(), STVELPLAN_setCfg(), STVELPLAN_setCfgHaltState(), and _ST_Obj::velPlanHandle.
Referenced by main().
void ST_setupVelPlan_GroceryConveyor (ST_Handle sthandle)
Definition at line 872 of file proj_lab06d.c.
References _IQ, _IQ20, _IQ24, GROCERY_Convey, GROCERY_Idle, GROCERY_OnOff, GROCERY_ProxBlocked, GROCERY_ProxOpen, GROCERY_ProxSensor, GROCERY_SwitchOff, GROCERY_SwitchOn, ST_SAMPLE_TIME, ST_SPEED_PU_PER_KRPM, STVELPLAN_addCfgCond(), STVELPLAN_addCfgState(), STVELPLAN_addCfgTran(), STVELPLAN_addCfgVar(), STVELPLAN_reset(), STVELPLAN_setCfg(), STVELPLAN_setCfgHaltState(), and _ST_Obj::velPlanHandle.
Referenced by main().
void ST_setupVelPlan_TestPattern (ST_Handle sthandle)
Definition at line 826 of file proj_lab06d.c.
References _IQ, _IQ20, _IQ24, ST_SAMPLE_TIME, ST_SPEED_PU_PER_KRPM, STVELPLAN_addCfgState(), STVELPLAN_addCfgTran(), STVELPLAN_reset(), STVELPLAN_setCfg(), STVELPLAN_setCfgHaltState(), TEST_0, TEST_1000, TEST_2000, TEST_250, TEST_4000, TEST_500, TEST_N1000, TEST_N2000, TEST_N250, TEST_N4000, TEST_N500, and _ST_Obj::velPlanHandle.
Referenced by main().
void updateGlobalVariables_motor (CTRL_Handle handle, ST_Handle sthandle)
Updates the global motor variables.
Definition at line 716 of file proj_lab06d.c.
References _IQ, _IQmpy, CTRL_getState(), _MOTOR_Vars_t_::CtrlState, _HAL_AdcData_t_::dcBus, EST_get_pu_to_krpm_sf(), EST_getFlux_VpHz(), EST_getIdRated(), EST_getLs_d_H(), EST_getLs_q_H(), EST_getRr_Ohm(), EST_getRs_Ohm(), EST_getSpeed_krpm(), EST_getState(), _CTRL_Obj_::estHandle, _MOTOR_Vars_t_::EstState, _MOTOR_Vars_t_::Flux_VpHz, _MOTOR_Vars_t_::Flux_Wb, _ST_Vars_t::FrictionEstimate_Aperkrpm, gFlux_pu_to_Wb_sf, gTorque_Flux_Iq_pu_to_Nm_sf, gTorque_Ls_Id_Iq_pu_to_Nm_sf, _ST_Vars_t::InertiaEstimate_Aperkrpm, _MOTOR_Vars_t_::IqRef_A, _MOTOR_Vars_t_::Lsd_H, _MOTOR_Vars_t_::Lsq_H, _MOTOR_Vars_t_::MagnCurr_A, _MOTOR_Vars_t_::Rr_Ohm, _MOTOR_Vars_t_::Rs_Ohm, _MOTOR_Vars_t_::Speed_krpm, _MOTOR_Vars_t_::SpeedTraj_krpm, _MOTOR_Vars_t_::SpinTAC, ST_SPEED_PU_PER_KRPM, STVELCTL_getErrorID(), STVELCTL_getFriction(), STVELCTL_getInertia(), STVELCTL_getStatus(), STVELCTL_getTorqueReference(), STVELMOVE_getErrorID(), STVELMOVE_getProfileTime_tick(), STVELMOVE_getStatus(), STVELMOVE_getVelocityReference(), STVELPLAN_getCfgError(), STVELPLAN_getStatus(), _MOTOR_Vars_t_::Torque_Nm, USER_computeFlux(), USER_computeTorque_Nm(), USER_IQ_FULL_SCALE_CURRENT_A, USER_IQ_FULL_SCALE_VOLTAGE_V, _MOTOR_Vars_t_::VdcBus_kV, _ST_Vars_t::VelCtlErrorID, _ST_Obj::velCtlHandle, _ST_Vars_t::VelCtlStatus, _ST_Vars_t::VelMoveErrorID, _ST_Obj::velMoveHandle, _ST_Vars_t::VelMoveStatus, _ST_Vars_t::VelMoveTime_ticks, _ST_Vars_t::VelPlanCfgErrorCode, _ST_Vars_t::VelPlanCfgErrorIdx, _ST_Vars_t::VelPlanErrorID, _ST_Obj::velPlanHandle, and _ST_Vars_t::VelPlanStatus.
Referenced by main().
void updateKpKiGains (CTRL_Handle handle)
Updates Kp and Ki gains in the controller object.
Definition at line 798 of file proj_lab06d.c.
References CTRL_setKi(), CTRL_setKp(), _MOTOR_Vars_t_::CtrlState, Flag_Latch_softwareUpdate, _MOTOR_Vars_t_::Flag_MotorIdentified, _MOTOR_Vars_t_::Ki_Idq, _MOTOR_Vars_t_::Ki_spd, _MOTOR_Vars_t_::Kp_Idq, and _MOTOR_Vars_t_::Kp_spd.
Referenced by main().
Variable Documentation
CTRL_Obj ctrl
Definition at line 97 of file proj_lab06d.c.
CTRL_Handle ctrlHandle
Definition at line 82 of file proj_lab06d.c.
bool Flag_Latch_softwareUpdate = true
Definition at line 80 of file proj_lab06d.c.
Referenced by main(), and updateKpKiGains().
HAL_AdcData_t gAdcData
Definition at line 90 of file proj_lab06d.c.
PLAN_SELECT_e gConfiguredPlan = TEST_PATTERN
Definition at line 110 of file proj_lab06d.c.
Referenced by main(), and ST_runVelPlan().
uint_least16_t gCounter_updateGlobals = 0
Definition at line 78 of file proj_lab06d.c.
Referenced by main().
_iq gFlux_pu_to_VpHz_sf
Definition at line 274 of file proj_lab06d.c.
Referenced by main().
_iq gFlux_pu_to_Wb_sf
Definition at line 272 of file proj_lab06d.c.
Referenced by main(), and updateGlobalVariables_motor().
_iq gGarageDoorButton = 0
Definition at line 255 of file proj_lab06d.c.
Referenced by ST_runVelPlan().
_iq gGarageDoorDown = 1
Definition at line 253 of file proj_lab06d.c.
Referenced by ST_runVelPlan().
_iq gGarageDoorUp = 0
Definition at line 254 of file proj_lab06d.c.
Referenced by ST_runVelPlan().
GARAGE_State_e gGarageState = GARAGE_Idle
Definition at line 252 of file proj_lab06d.c.
Referenced by ST_runVelPlan().
_iq gGroceryConveyorOnOff = 0
Definition at line 248 of file proj_lab06d.c.
Referenced by ST_runVelPlan().
_iq gGroceryConveyorProxSensor = 0
Definition at line 249 of file proj_lab06d.c.
Referenced by ST_runVelPlan().
GROCERY_State_e gGroceryState = GROCERY_Idle
Definition at line 247 of file proj_lab06d.c.
Referenced by ST_runVelPlan().
uint16_t gLEDcnt = 0
Definition at line 257 of file proj_lab06d.c.
Referenced by mainISR().
_iq gMaxCurrentSlope = _IQ(0.0)
Definition at line 92 of file proj_lab06d.c.
Referenced by main().
volatile MOTOR_Vars_t gMotorVars = MOTOR_Vars_INIT
Definition at line 259 of file proj_lab06d.c.
HAL_PwmData_t gPwmData = {_IQ(0.0), _IQ(0.0), _IQ(0.0)}
Definition at line 88 of file proj_lab06d.c.
PLAN_SELECT_e gSelectedPlan = TEST_PATTERN
Definition at line 107 of file proj_lab06d.c.
Referenced by main(), and ST_runVelPlan().
TEST_State_e gTestState = TEST_0
Definition at line 244 of file proj_lab06d.c.
Referenced by ST_runVelPlan().
_iq gTorque_Flux_Iq_pu_to_Nm_sf
Definition at line 278 of file proj_lab06d.c.
Referenced by main(), and updateGlobalVariables_motor().
_iq gTorque_Ls_Id_Iq_pu_to_Nm_sf
Definition at line 276 of file proj_lab06d.c.
Referenced by main(), and updateGlobalVariables_motor().
USER_Params gUserParams
Definition at line 86 of file proj_lab06d.c.
ST_PlanButton_e gVelPlanRunFlag = ST_PLAN_STOP
Definition at line 104 of file proj_lab06d.c.
Referenced by ST_runVelPlan().
HAL_Handle halHandle
Definition at line 84 of file proj_lab06d.c.
ST_Obj st_obj
Definition at line 100 of file proj_lab06d.c.
ST_Handle stHandle
Definition at line 101 of file proj_lab06d.c.
Referenced by main(), and mainISR().
uint32_t stVelPlanCfgArray[ST_VELPLAN_CFG_ARRAY_DWORDS]
Definition at line 241 of file proj_lab06d.c.
Referenced by ST_setupVelPlan().