instaspin_motion: PROJ_LAB12b
PROJ_LAB12b
Modules
Project Overview
Macros
#define LED_BLINK_FREQ_Hz 5
Functions
void main (void)
interrupt void mainISR (void)
The main interrupt service (ISR) routine.
void updateGlobalVariables_motor (CTRL_Handle handle, ST_Handle sthandle)
Updates the global motor variables.
void updateKpKiGains (CTRL_Handle handle)
Updates Kp and Ki gains in the controller object.
void ST_runPosConv (ST_Handle handle, ENC_Handle encHandle, CTRL_Handle ctrlHandle)
Runs SpinTAC Positon Convert.
void ST_runVelCtl (ST_Handle handle, CTRL_Handle ctrlHandle)
Runs SpinTAC Velocity Control.
Variables
uint_least16_t gCounter_updateGlobals = 0
bool Flag_Latch_softwareUpdate = true
CTRL_Handle ctrlHandle
HAL_Handle halHandle
USER_Params gUserParams
HAL_PwmData_t gPwmData = {_IQ(0.0), _IQ(0.0), _IQ(0.0)}
HAL_AdcData_t gAdcData
_iq gMaxCurrentSlope = _IQ(0.0)
CTRL_Obj ctrl
ENC_Handle encHandle
ENC_Obj enc
SLIP_Handle slipHandle
SLIP_Obj slip
ST_Obj st_obj
ST_Handle stHandle
uint16_t gLEDcnt = 0
volatile MOTOR_Vars_t gMotorVars = MOTOR_Vars_INIT
_iq gFlux_pu_to_Wb_sf
_iq gFlux_pu_to_VpHz_sf
_iq gTorque_Ls_Id_Iq_pu_to_Nm_sf
_iq gTorque_Flux_Iq_pu_to_Nm_sf
Detailed Description
Macro Definition Documentation
#define LED_BLINK_FREQ_Hz 5
Definition at line 65 of file proj_lab12b.c.
Referenced by mainISR().
Function Documentation
void main (void)
Definition at line 128 of file proj_lab12b.c.
References _IQ, _IQmpy, CTRL_getFlag_enableUserMotorParams(), CTRL_getKi(), CTRL_getKp(), CTRL_getState(), CTRL_getVersion(), CTRL_initCtrl(), CTRL_isError(), CTRL_setFlag_enableCtrl(), CTRL_setFlag_enableDcBusComp(), CTRL_setFlag_enableOffset(), CTRL_setFlag_enablePowerWarp(), CTRL_setFlag_enableSpeedCtrl(), CTRL_setFlag_enableUserMotorParams(), CTRL_setMaxAccel_pu(), CTRL_setParams(), CTRL_setSpd_ref_krpm(), CTRL_updateState(), _USER_Params_::ctrlPeriod_sec, _MOTOR_Vars_t_::CtrlVersion, ENC_init(), ENC_setup(), EST_getMaxCurrentSlope_pu(), EST_getState(), EST_isMotorIdentified(), EST_setFlag_enableForceAngle(), EST_setFlag_enableRsRecalc(), EST_setMaxCurrentSlope_pu(), _CTRL_Obj_::estHandle, _MOTOR_Vars_t_::Flag_enableForceAngle, _MOTOR_Vars_t_::Flag_enableOffsetcalc, _MOTOR_Vars_t_::Flag_enablePowerWarp, _MOTOR_Vars_t_::Flag_enableRsRecalc, _MOTOR_Vars_t_::Flag_enableSys, _MOTOR_Vars_t_::Flag_enableUserParams, Flag_Latch_softwareUpdate, _MOTOR_Vars_t_::Flag_MotorIdentified, _MOTOR_Vars_t_::Flag_Run_Identify, gCounter_updateGlobals, gFlux_pu_to_VpHz_sf, gFlux_pu_to_Wb_sf, gMaxCurrentSlope, gTorque_Flux_Iq_pu_to_Nm_sf, gTorque_Ls_Id_Iq_pu_to_Nm_sf, hal, HAL_disablePwm(), HAL_enableAdcInts(), HAL_enableDebugInt(), HAL_enableDrv(), HAL_enableGlobalInts(), HAL_enablePwm(), HAL_getBias(), HAL_init(), HAL_initIntVectorTable(), HAL_readDrvData(), HAL_setBias(), HAL_setParams(), HAL_setupDrvSpi(), HAL_setupFaults(), HAL_updateAdcBias(), HAL_writeDrvData(), I_A_offset, I_B_offset, _MOTOR_Vars_t_::I_bias, I_C_offset, _MOTOR_Vars_t_::Ki_Idq, _MOTOR_Vars_t_::Kp_Idq, MAX_ACCEL_KRPMPS_SF, _MOTOR_Vars_t_::MaxAccel_krpmps, memCopy(), _CTRL_Version_::minor, NUM_MAIN_TICKS_FOR_GLOBAL_VARIABLE_UPDATE, SLIP_init(), SLIP_setup(), slipHandle, _MOTOR_Vars_t_::SpeedRef_krpm, _MOTOR_Vars_t_::SpinTAC, ST_init(), ST_setupPosConv(), ST_setupVelCtl(), stHandle, STVELCTL_getBandwidth_radps(), STVELCTL_getOutputMaximum(), STVELCTL_getOutputMinimum(), STVELCTL_setBandwidth_radps(), STVELCTL_setEnable(), STVELCTL_setOutputMaximums(), updateGlobalVariables_motor(), updateKpKiGains(), USER_calcPIgains(), USER_checkForErrors(), USER_computeFlux_pu_to_VpHz_sf(), USER_computeFlux_pu_to_Wb_sf(), USER_computeTorque_Flux_Iq_pu_to_Nm_sf(), USER_computeTorque_Ls_Id_Iq_pu_to_Nm_sf(), USER_getErrorCode(), USER_IQ_FULL_SCALE_CURRENT_A, USER_IQ_FULL_SCALE_FREQ_Hz, USER_ISR_FREQ_Hz, USER_MOTOR_ENCODER_LINES, USER_MOTOR_NUM_POLE_PAIRS, USER_setParams(), USER_softwareUpdate1p6(), _MOTOR_Vars_t_::UserErrorCode, V_A_offset, V_B_offset, _MOTOR_Vars_t_::V_bias, V_C_offset, _MATH_vec3_::value, _ST_Vars_t::VelCtlBw_radps, _ST_Obj::velCtlHandle, _ST_Vars_t::VelCtlOutputMax_A, and _ST_Vars_t::VelCtlOutputMin_A.
interrupt void mainISR (void)
The main interrupt service (ISR) routine.
Definition at line 472 of file proj_lab12b.c.
References CTRL_run(), CTRL_setup(), ENC_calcElecAngle(), ENC_getElecAngle(), ENC_setZeroOffset(), EST_getState(), _CTRL_Obj_::estHandle, gLEDcnt, HAL_acqAdcInt(), HAL_readAdcData(), HAL_toggleLed, HAL_writePwmData(), ISR_TICKS_PER_SPINTAC_TICK, LED_BLINK_FREQ_Hz, SLIP_getMagneticAngle(), SLIP_run(), SLIP_setElectricalAngle(), slipHandle, ST_runPosConv(), ST_runVelCtl(), stHandle, USER_ISR_FREQ_Hz, and USER_MOTOR_TYPE.
void ST_runPosConv (ST_Handle handle, ENC_Handle encHandle, CTRL_Handle ctrlHandle)
Runs SpinTAC Positon Convert.
Definition at line 627 of file proj_lab12b.c.
References CTRL_getIdq_in_addr(), ENC_getElecAngle(), _ST_Obj::posConvHandle, SLIP_setSlipVelocity(), slipHandle, STPOSCONV_getSlipVelocity(), STPOSCONV_run(), STPOSCONV_setCurrentVector(), STPOSCONV_setElecAngle_erev(), and USER_MOTOR_TYPE.
Referenced by mainISR().
void ST_runVelCtl (ST_Handle handle, CTRL_Handle ctrlHandle)
Runs SpinTAC Velocity Control.
Definition at line 651 of file proj_lab12b.c.
References _IQ, CTRL_setIq_ref_pu(), EST_getFm_pu(), _CTRL_Obj_::estHandle, _ST_Obj::posConvHandle, STPOSCONV_getVelocityFiltered(), STVELCTL_getTorqueReference(), STVELCTL_run(), STVELCTL_setAccelerationReference(), STVELCTL_setVelocityFeedback(), STVELCTL_setVelocityReference(), TRAJ_getIntValue(), _CTRL_Obj_::trajHandle_spd, and _ST_Obj::velCtlHandle.
Referenced by mainISR().
void updateGlobalVariables_motor (CTRL_Handle handle, ST_Handle sthandle)
Updates the global motor variables.
Definition at line 538 of file proj_lab12b.c.
References _IQ, _IQmpy, CTRL_getSpd_int_ref_pu(), CTRL_getState(), _MOTOR_Vars_t_::CtrlState, _HAL_AdcData_t_::dcBus, EST_get_pu_to_krpm_sf(), EST_getFlux_VpHz(), EST_getIdRated(), EST_getLs_d_H(), EST_getLs_q_H(), EST_getRr_Ohm(), EST_getRs_Ohm(), EST_getSpeed_krpm(), EST_getState(), _CTRL_Obj_::estHandle, _MOTOR_Vars_t_::EstState, _MOTOR_Vars_t_::Flux_VpHz, _MOTOR_Vars_t_::Flux_Wb, _ST_Vars_t::FrictionEstimate_Aperkrpm, gFlux_pu_to_Wb_sf, gTorque_Flux_Iq_pu_to_Nm_sf, gTorque_Ls_Id_Iq_pu_to_Nm_sf, _ST_Vars_t::InertiaEstimate_Aperkrpm, _MOTOR_Vars_t_::IqRef_A, _MOTOR_Vars_t_::Lsd_H, _MOTOR_Vars_t_::Lsq_H, _MOTOR_Vars_t_::MagnCurr_A, _ST_Vars_t::PosConvErrorID, _ST_Obj::posConvHandle, _MOTOR_Vars_t_::Rr_Ohm, _MOTOR_Vars_t_::Rs_Ohm, _MOTOR_Vars_t_::Speed_krpm, _MOTOR_Vars_t_::SpeedQEP_krpm, _MOTOR_Vars_t_::SpeedTraj_krpm, _MOTOR_Vars_t_::SpinTAC, ST_SPEED_KRPM_PER_PU, ST_SPEED_PU_PER_KRPM, STPOSCONV_getErrorID(), STPOSCONV_getVelocityFiltered(), STVELCTL_getErrorID(), STVELCTL_getFriction(), STVELCTL_getInertia(), STVELCTL_getStatus(), STVELCTL_getTorqueReference(), _MOTOR_Vars_t_::Torque_Nm, USER_computeFlux(), USER_computeTorque_Nm(), USER_IQ_FULL_SCALE_CURRENT_A, USER_IQ_FULL_SCALE_VOLTAGE_V, _MOTOR_Vars_t_::VdcBus_kV, _ST_Vars_t::VelCtlErrorID, _ST_Obj::velCtlHandle, and _ST_Vars_t::VelCtlStatus.
Referenced by main().
void updateKpKiGains (CTRL_Handle handle)
Updates Kp and Ki gains in the controller object.
Definition at line 608 of file proj_lab12b.c.
References CTRL_setKi(), CTRL_setKp(), _MOTOR_Vars_t_::CtrlState, Flag_Latch_softwareUpdate, _MOTOR_Vars_t_::Flag_MotorIdentified, _MOTOR_Vars_t_::Ki_Idq, _MOTOR_Vars_t_::Ki_spd, _MOTOR_Vars_t_::Kp_Idq, and _MOTOR_Vars_t_::Kp_spd.
Referenced by main().
Variable Documentation
CTRL_Obj ctrl
Definition at line 90 of file proj_lab12b.c.
CTRL_Handle ctrlHandle
Definition at line 75 of file proj_lab12b.c.
ENC_Obj enc
Definition at line 94 of file proj_lab12b.c.
ENC_Handle encHandle
Definition at line 93 of file proj_lab12b.c.
bool Flag_Latch_softwareUpdate = true
Definition at line 73 of file proj_lab12b.c.
Referenced by main(), and updateKpKiGains().
HAL_AdcData_t gAdcData
Definition at line 83 of file proj_lab12b.c.
uint_least16_t gCounter_updateGlobals = 0
Definition at line 71 of file proj_lab12b.c.
Referenced by main().
_iq gFlux_pu_to_VpHz_sf
Definition at line 119 of file proj_lab12b.c.
Referenced by main().
_iq gFlux_pu_to_Wb_sf
Definition at line 117 of file proj_lab12b.c.
Referenced by main(), and updateGlobalVariables_motor().
uint16_t gLEDcnt = 0
Definition at line 102 of file proj_lab12b.c.
Referenced by mainISR().
_iq gMaxCurrentSlope = _IQ(0.0)
Definition at line 85 of file proj_lab12b.c.
Referenced by main().
volatile MOTOR_Vars_t gMotorVars = MOTOR_Vars_INIT
Definition at line 104 of file proj_lab12b.c.
HAL_PwmData_t gPwmData = {_IQ(0.0), _IQ(0.0), _IQ(0.0)}
Definition at line 81 of file proj_lab12b.c.
_iq gTorque_Flux_Iq_pu_to_Nm_sf
Definition at line 123 of file proj_lab12b.c.
Referenced by main(), and updateGlobalVariables_motor().
_iq gTorque_Ls_Id_Iq_pu_to_Nm_sf
Definition at line 121 of file proj_lab12b.c.
Referenced by main(), and updateGlobalVariables_motor().
USER_Params gUserParams
Definition at line 79 of file proj_lab12b.c.
HAL_Handle halHandle
Definition at line 77 of file proj_lab12b.c.
SLIP_Obj slip
Definition at line 97 of file proj_lab12b.c.
SLIP_Handle slipHandle
Definition at line 96 of file proj_lab12b.c.
Referenced by main(), mainISR(), and ST_runPosConv().
ST_Obj st_obj
Definition at line 99 of file proj_lab12b.c.
ST_Handle stHandle
Definition at line 100 of file proj_lab12b.c.
Referenced by main(), and mainISR().