instaspin_motion: ST
ST
Data Structures
struct _POS_Params_t
Defines the position components of SpinTAC (ST)
struct _ST_Obj
Defines the SpinTAC (ST) object.
struct _ST_Vars_t
Defines the SpinTAC (ST) global variables.
struct _VEL_Params_t
Defines the velocity components of SpinTAC (ST)
Macros
#define ST_MREV_ROLLOVER (10.0)
ROTATION UNIT MAXIMUMS.
#define ST_EREV_MAXIMUM (1.0)
Defines the maximum value for an Electrical Revolution [ERev].
#define ST_POS_ERROR_MAXIMUM_MREV (2.0)
Defines the maximum value of error allowable in SpinTAC Position Control, MRev This value should be the maximum amount of position error that is allowable in your system. If the position error exceeds this value, SpinTAC Position Control will hold it's output to 0.
#define ISR_TICKS_PER_SPINTAC_TICK (USER_NUM_ISR_TICKS_PER_CTRL_TICK * USER_NUM_CTRL_TICKS_PER_SPEED_TICK)
SAMPLE TIME.
#define ST_SAMPLE_TIME (ISR_TICKS_PER_SPINTAC_TICK / USER_ISR_FREQ_Hz)
Defines the SpinTAC execution period, sec.
#define ST_SPEED_PU_PER_KRPM (USER_MOTOR_NUM_POLE_PAIRS / (0.001 * 60.0 * USER_IQ_FULL_SCALE_FREQ_Hz))
UNIT SCALING.
#define ST_SPEED_KRPM_PER_PU ((0.001 * 60.0 * USER_IQ_FULL_SCALE_FREQ_Hz) / USER_MOTOR_NUM_POLE_PAIRS)
Defines the speed scale factor for the system.
#define ST_SYSTEM_INERTIA_PU (USER_SYSTEM_INERTIA * ST_SPEED_KRPM_PER_PU * (1.0 / USER_IQ_FULL_SCALE_CURRENT_A))
Defines the default inertia for the system, PU/(pu/s^2)
#define ST_SYSTEM_FRICTION_PU (USER_SYSTEM_FRICTION * ST_SPEED_KRPM_PER_PU * (1.0 / USER_IQ_FULL_SCALE_CURRENT_A))
Defines the default friction for the system, PU/(pu/s^2)
#define ST_MIN_ID_SPEED_RPM (5)
SPINTAC IDENTIFY SETTINGS.
#define ST_MIN_ID_SPEED_PU (ST_MIN_ID_SPEED_RPM * 0.001 * ST_SPEED_PU_PER_KRPM)
Defines the minimum speed from which the SpinTAC Identify will start running Compile time calculation that converts the minimum identification speed into pu/s.
#define ST_ID_INCOMPLETE_ERROR (2005)
Defines the SpinTAC Identify error code that needs to run to completion Identifies the error code that should not halt operation.
#define ST_VARS_DEFAULTS
GLOBAL VARIABLE INITIALIZATION.
#define ISR_TICKS_PER_SPINTAC_TICK (USER_NUM_ISR_TICKS_PER_CTRL_TICK * USER_NUM_CTRL_TICKS_PER_SPEED_TICK)
SAMPLE TIME.
#define ST_SAMPLE_TIME (ISR_TICKS_PER_SPINTAC_TICK / USER_ISR_FREQ_Hz)
Defines the SpinTAC execution period, sec.
#define ST_SPEED_PU_PER_KRPM (USER_MOTOR_NUM_POLE_PAIRS / (0.001 * 60.0 * USER_IQ_FULL_SCALE_FREQ_Hz))
UNIT SCALING.
#define ST_SPEED_KRPM_PER_PU ((0.001 * 60.0 * USER_IQ_FULL_SCALE_FREQ_Hz) / USER_MOTOR_NUM_POLE_PAIRS)
Defines the speed scale factor for the system.
#define ST_SYSTEM_INERTIA_PU (USER_SYSTEM_INERTIA * ST_SPEED_KRPM_PER_PU * (1.0 / USER_IQ_FULL_SCALE_CURRENT_A))
Defines the default inertia for the system, PU/(pu/s^2)
#define ST_SYSTEM_FRICTION_PU (USER_SYSTEM_FRICTION * ST_SPEED_KRPM_PER_PU * (1.0 / USER_IQ_FULL_SCALE_CURRENT_A))
Defines the default friction for the system, PU/(pu/s^2)
#define ST_MIN_ID_SPEED_RPM (5)
SPINTAC IDENTIFY SETTINGS.
#define ST_MIN_ID_SPEED_PU (ST_MIN_ID_SPEED_RPM * 0.001 * ST_SPEED_PU_PER_KRPM)
Defines the minimum speed from which the SpinTAC Identify will start running Compile time calculation that converts the minimum identification speed into pu/s.
#define ST_ID_INCOMPLETE_ERROR (2005)
Defines the SpinTAC Identify error code that needs to run to completion Identifies the error code that should not halt operation.
#define ST_VARS_DEFAULTS
GLOBAL VARIABLE INITIALIZATION.
Typedefs
typedef struct _POS_Params_t POS_Params_t
Defines the position components of SpinTAC (ST)
typedef struct _ST_Obj ST_Obj
Defines the SpinTAC (ST) object.
typedef struct _ST_Obj_ * ST_Handle
Handle.
typedef struct _ST_Vars_t ST_Vars_t
Defines the SpinTAC (ST) global variables.
typedef struct _VEL_Params_t VEL_Params_t
Defines the velocity components of SpinTAC (ST)
typedef struct _ST_Obj ST_Obj
Defines the SpinTAC (ST) object.
typedef struct _ST_Obj_ * ST_Handle
Handle.
typedef struct _ST_Vars_t ST_Vars_t
Defines the SpinTAC (ST) global variables.
Enumerations
enum ST_PlanButton_e {
ST_PLAN_STOP = 0, ST_PLAN_START, ST_PLAN_PAUSE, ST_PLAN_STOP = 0,
ST_PLAN_START, ST_PLAN_PAUSE
}
Enumeration for the control of the position motion state machine (SpinTAC Position Plan)
enum ST_PlanButton_e {
ST_PLAN_STOP = 0, ST_PLAN_START, ST_PLAN_PAUSE, ST_PLAN_STOP = 0,
ST_PLAN_START, ST_PLAN_PAUSE
}
Enumeration for the control of the velocity motion state machine (SpinTAC Velocity Plan)
Functions
ST_Handle ST_init (void *pMemory, const size_t numBytes)
Initalizes the SpinTAC (ST) object.
void ST_setupPosConv (ST_Handle handle)
Setups SpinTAC Position Convert.
void ST_setupPosCtl (ST_Handle handle)
Setups SpinTAC Position Control.
void ST_setupPosMove (ST_Handle handle)
Setups SpinTAC Position Move.
void ST_setupPosPlan (ST_Handle)
Setups SpinTAC Positon Plan.
void ST_runPosPlanTick (ST_Handle handle)
Runs the time-critical components of SpinTAC Positon Plan.
void ST_runPosConv (ST_Handle, ENC_Handle, CTRL_Handle)
Runs SpinTAC Positon Convert.
void ST_runPosCtl (ST_Handle, CTRL_Handle)
Runs SpinTAC Positon Control.
void ST_runPosMove (ST_Handle)
Runs SpinTAC Positon Move.
void ST_runPosPlan (ST_Handle)
Runs SpinTAC Positon Plan.
void ST_setupVelCtl (ST_Handle handle)
Setups SpinTAC Velocity Control.
void ST_setupVelMove (ST_Handle handle)
Setups SpinTAC Velocity Move.
void ST_setupVelPlan (ST_Handle)
Setups SpinTAC Velocity Plan.
void ST_runVelPlanTick (ST_Handle handle)
Runs the time-critical components of SpinTAC Velocity Plan.
void ST_setupVelId (ST_Handle handle)
Setups SpinTAC Velocity Identify.
void ST_runVelCtl (ST_Handle, CTRL_Handle)
Runs SpinTAC Velocity Control.
void ST_runVelMove (ST_Handle, CTRL_Handle)
Runs SpinTAC Velocity Move.
void ST_runVelPlan (ST_Handle, CTRL_Handle)
Runs SpinTAC Velocity Plan.
void ST_runVelId (ST_Handle, CTRL_Handle)
Runs SpinTAC Velocity Identify.
Detailed Description
Data Structure Documentation
struct _POS_Params_t
Defines the position components of SpinTAC (ST)
Definition at line 157 of file spintac_position.h.
Data Fields
ST_PosConv_t conv the position converter (ST_PosConv) object
ST_PosCtl_t ctl the position controller (ST_PosCtl) object
ST_PosMove_t move the position profile generator (ST_PosMove) object
ST_PosPlan_t plan the position motion sequencer (ST_PosPlan) object
struct _ST_Obj
Defines the SpinTAC (ST) object.
Definition at line 167 of file spintac_position.h.
Data Fields
POS_Params_t pos the position components of the SpinTAC (ST) object
ST_POSCONV_Handle posConvHandle Handle for Position Converter (ST_PosConv)
ST_POSCTL_Handle posCtlHandle Handle for Position Controller (ST_PosCtl)
ST_POSMOVE_Handle posMoveHandle Handle for Position Move (ST_PosMove)
ST_POSPLAN_Handle posPlanHandle Handle for Position Plan (ST_PosPlan)
VEL_Params_t vel the velocity components of the SpinTAC (ST) object
ST_VELCTL_Handle velCtlHandle Handle for Velocity Controller (ST_VelCtl)
ST_VELID_Handle velIdHandle Handle for Velocity Identify (ST_VelId)
ST_VELMOVE_Handle velMoveHandle Handle for Velocity Move (ST_VelMove)
ST_VELPLAN_Handle velPlanHandle Handle for Velocity Plan (ST_VelPlan)
ST_Ver_t version the version (ST_Ver) object
ST_VER_Handle versionHandle Handle for Version (ST_Ver)
struct _ST_Vars_t
Defines the SpinTAC (ST) global variables.
Definition at line 193 of file spintac_position.h.
Data Fields
_iq24 FrictionEstimate_Aperkrpm displays the friction used by Position Controller (ST_PosCtl)
displays the friction estimated by Velocity Identify (ST_VelId) and used by Velocity Controller (ST_VelCtl)
_iq24 InertiaEstimate_Aperkrpm displays the inertia used by Position Controller (ST_PosCtl)
displays the inertia estimated by Velocity Identify (ST_VelId) and used by Velocity Controller (ST_VelCtl)
uint16_t PosConvErrorID displays the error seen by the Position Converter (ST_PosConv)
_iq20 PosCtlBw_radps sets the tuning (Bw_radps) of the Position Controller (ST_PosCtl)
uint16_t PosCtlErrorID displays the error seen by Position Controller (ST_PosCtl)
_iq24 PosCtlOutputMax_A sets the maximum amount of current the Position Controller (ST_PosCtl) will supply as Iq reference
_iq24 PosCtlOutputMin_A sets the minimum amount of current the Position Controller (ST_PosCtl) will supply as Iq reference
ST_CtlStatus_e PosCtlStatus status of Position Controller (ST_PosCtl)
ST_MoveCurveType_e PosMoveCurveType selects the curve type used by Position Move (ST_PosMove)
uint16_t PosMoveErrorID displays the error seen by Position Move (ST_PosMove)
ST_MoveStatus_e PosMoveStatus status of Position Move (ST_PosMove)
int32_t PosMoveTime_mticks Profile time million tick part value, together with ProTime_tick to present the total amount of time (ST_PosMove)
int32_t PosMoveTime_ticks Amount of time profile will take within 1 million ticks (ST_PosMove)
uint16_t PosPlanCfgErrorCode displays the specific configuration error in Position Plan (ST_PosPlan)
uint16_t PosPlanCfgErrorIdx displays which index caused a configuration error in Position Plan (ST_PosPlan)
uint16_t PosPlanErrorID displays the error seen by Position Plan (ST_PosPlan)
ST_PlanButton_e PosPlanRun contols the operation of Position Plan (ST_PosPlan)
ST_PlanStatus_e PosPlanStatus status of Position Plan (ST_PosPlan)
_iq20 VelCtlBw_radps sets the tuning (Bw_radps) of the Velocity Controller (ST_VelCtl)
bool VelCtlEnb selects the velocity controller to use { true: SpinTAC false: PI }
uint16_t VelCtlErrorID displays the error seen by Velocity Controller (ST_VelCtl)
_iq24 VelCtlOutputMax_A sets the maximum amount of current the Velocity Controller (ST_VelCtl) will supply as Iq reference
_iq24 VelCtlOutputMin_A sets the minimum amount of current the Velocity Controller (ST_VelCtl) will supply as Iq reference
ST_CtlStatus_e VelCtlStatus status of Velocity Controller (ST_VelCtl)
uint16_t VelIdErrorID displays the error seen by Velocity Identify (ST_VelId)
_iq24 VelIdGoalSpeed_krpm sets the goal speed of Velocity Identify (ST_VelId)
bool VelIdRun controls the operation of the Velocity Identify (ST_VelId)
ST_VelIdStatus_e VelIdStatus status of Velocity Identify (ST_VelId)
_iq24 VelIdTorqueRampTime_sec sets the rate at which torque is applied during Identification (ST_VelId)
ST_MoveCurveType_e VelMoveCurveType selects the curve type used by Velocity Move (ST_VelMove)
uint16_t VelMoveErrorID displays the error seen by Velocity Move (ST_VelMove)
ST_MoveStatus_e VelMoveStatus status of Velocity Move (ST_VelMove)
int32_t VelMoveTime_ticks displys the time that the current profile will take { unit: [ticks] } (ST_VelMove)
uint16_t VelPlanCfgErrorCode displays the specific configuration error in Velocity Plan (ST_VelPlan)
uint16_t VelPlanCfgErrorIdx displays which index caused a configuration error in Velocity Plan (ST_VelPlan)
uint16_t VelPlanErrorID displays the error seen by Velocity Plan (ST_VelPlan)
ST_PlanButton_e VelPlanRun contols the operation of Velocity Plan (ST_VelPlan)
ST_PlanStatus_e VelPlanStatus status of Velocity Plan (ST_VelPlan)
struct _VEL_Params_t
Defines the velocity components of SpinTAC (ST)
Definition at line 143 of file spintac_velocity.h.
Data Fields
ST_PosConv_t conv the position converter (ST_PosConv) object
ST_VelCtl_t ctl the velocity controller (ST_VelCtl) object
ST_VelId_t id the velocity identify (ST_VelId) object
ST_VelMove_t move the velocity profile generator (ST_VelMove) object
ST_VelPlan_t plan the velocity motion sequence generator (ST_VelPlan) object
Macro Definition Documentation
#define ISR_TICKS_PER_SPINTAC_TICK (USER_NUM_ISR_TICKS_PER_CTRL_TICK * USER_NUM_CTRL_TICKS_PER_SPEED_TICK)
SAMPLE TIME.
Defines the number of interrupt ticks per SpinTAC tick Should be the same as the InstSpin-FOC speed controller clock tick
Definition at line 71 of file spintac_velocity.h.
#define ISR_TICKS_PER_SPINTAC_TICK (USER_NUM_ISR_TICKS_PER_CTRL_TICK * USER_NUM_CTRL_TICKS_PER_SPEED_TICK)
SAMPLE TIME.
Defines the number of interrupt ticks per SpinTAC tick Should be the same as the InstSpin-FOC speed controller clock tick
Definition at line 90 of file spintac_position.h.
Referenced by mainISR().
#define ST_EREV_MAXIMUM (1.0)
Defines the maximum value for an Electrical Revolution [ERev].
The position siganl produced by the ENC module is a sawtooth signal This signal varies from 0 to the value specified in ST_EREV_MAXIMUM
Definition at line 78 of file spintac_position.h.
Referenced by ST_setupPosConv().
#define ST_ID_INCOMPLETE_ERROR (2005)
Defines the SpinTAC Identify error code that needs to run to completion Identifies the error code that should not halt operation.
Definition at line 108 of file spintac_velocity.h.
#define ST_ID_INCOMPLETE_ERROR (2005)
Defines the SpinTAC Identify error code that needs to run to completion Identifies the error code that should not halt operation.
Definition at line 127 of file spintac_position.h.
Referenced by ST_runVelId().
#define ST_MIN_ID_SPEED_PU (ST_MIN_ID_SPEED_RPM * 0.001 * ST_SPEED_PU_PER_KRPM)
Defines the minimum speed from which the SpinTAC Identify will start running Compile time calculation that converts the minimum identification speed into pu/s.
Definition at line 104 of file spintac_velocity.h.
#define ST_MIN_ID_SPEED_PU (ST_MIN_ID_SPEED_RPM * 0.001 * ST_SPEED_PU_PER_KRPM)
Defines the minimum speed from which the SpinTAC Identify will start running Compile time calculation that converts the minimum identification speed into pu/s.
Definition at line 123 of file spintac_position.h.
Referenced by ST_runVelId(), ST_runVelMove(), and ST_runVelPlan().
#define ST_MIN_ID_SPEED_RPM (5)
SPINTAC IDENTIFY SETTINGS.
Defines the minimum speed from which the SpinTAC Identify will start running, rpm This value needs to be low enough that the motor is effectivly stopped
Definition at line 100 of file spintac_velocity.h.
#define ST_MIN_ID_SPEED_RPM (5)
SPINTAC IDENTIFY SETTINGS.
Defines the minimum speed from which the SpinTAC Identify will start running, rpm This value needs to be low enough that the motor is effectivly stopped
Definition at line 119 of file spintac_position.h.
#define ST_MREV_ROLLOVER (10.0)
ROTATION UNIT MAXIMUMS.
Defines the maximum and minimum value at which the Mechanical Revolution [MRev] will rollover. The position signal produced by SpinTAC Position Converter is a sawtooth signal. All SpinTAC Components need to be aware of the bounds of this signal. When the position signal reaches the maximum value it will immediatly go to the minimum value. The minimum value is the negative of the maximum value.
Definition at line 73 of file spintac_position.h.
Referenced by ST_setupPosConv(), ST_setupPosCtl(), and ST_setupPosMove().
#define ST_POS_ERROR_MAXIMUM_MREV (2.0)
Defines the maximum value of error allowable in SpinTAC Position Control, MRev This value should be the maximum amount of position error that is allowable in your system. If the position error exceeds this value, SpinTAC Position Control will hold it's output to 0.
Definition at line 83 of file spintac_position.h.
Referenced by ST_setupPosCtl().
#define ST_SAMPLE_TIME (ISR_TICKS_PER_SPINTAC_TICK / USER_ISR_FREQ_Hz)
Defines the SpinTAC execution period, sec.
Definition at line 74 of file spintac_velocity.h.
Referenced by ST_setupVelCtl(), ST_setupVelId(), and ST_setupVelMove().
#define ST_SAMPLE_TIME (ISR_TICKS_PER_SPINTAC_TICK / USER_ISR_FREQ_Hz)
Defines the SpinTAC execution period, sec.
Definition at line 93 of file spintac_position.h.
Referenced by ST_setupPosConv(), ST_setupPosCtl(), ST_setupPosMove(), ST_setupPosPlan(), ST_setupVelPlan(), ST_setupVelPlan_GarageDoor(), ST_setupVelPlan_GroceryConveyor(), and ST_setupVelPlan_TestPattern().
#define ST_SPEED_KRPM_PER_PU ((0.001 * 60.0 * USER_IQ_FULL_SCALE_FREQ_Hz) / USER_MOTOR_NUM_POLE_PAIRS)
Defines the speed scale factor for the system.
Compile time calculation for scale factor (ratio) used throughout the system
Definition at line 85 of file spintac_velocity.h.
#define ST_SPEED_KRPM_PER_PU ((0.001 * 60.0 * USER_IQ_FULL_SCALE_FREQ_Hz) / USER_MOTOR_NUM_POLE_PAIRS)
Defines the speed scale factor for the system.
Compile time calculation for scale factor (ratio) used throughout the system
Definition at line 104 of file spintac_position.h.
Referenced by main(), ST_runPosPlan(), ST_runVelPlan(), and updateGlobalVariables_motor().
#define ST_SPEED_PU_PER_KRPM (USER_MOTOR_NUM_POLE_PAIRS / (0.001 * 60.0 * USER_IQ_FULL_SCALE_FREQ_Hz))
UNIT SCALING.
Defines the speed scale factor for the system Compile time calculation for scale factor (ratio) used throughout the system
Definition at line 81 of file spintac_velocity.h.
Referenced by ST_setupVelId().
#define ST_SPEED_PU_PER_KRPM (USER_MOTOR_NUM_POLE_PAIRS / (0.001 * 60.0 * USER_IQ_FULL_SCALE_FREQ_Hz))
UNIT SCALING.
Defines the speed scale factor for the system Compile time calculation for scale factor (ratio) used throughout the system
Definition at line 100 of file spintac_position.h.
Referenced by ST_runPosMove(), ST_runVelId(), ST_runVelMove(), ST_setupPosCtl(), ST_setupPosMove(), ST_setupPosPlan(), ST_setupVelPlan(), ST_setupVelPlan_GarageDoor(), ST_setupVelPlan_GroceryConveyor(), ST_setupVelPlan_TestPattern(), and updateGlobalVariables_motor().
#define ST_SYSTEM_FRICTION_PU (USER_SYSTEM_FRICTION * ST_SPEED_KRPM_PER_PU * (1.0 / USER_IQ_FULL_SCALE_CURRENT_A))
Defines the default friction for the system, PU/(pu/s^2)
This value should be calculated from the friction estimated with SpinTAC Identify
Definition at line 93 of file spintac_velocity.h.
Referenced by ST_setupVelCtl().
#define ST_SYSTEM_FRICTION_PU (USER_SYSTEM_FRICTION * ST_SPEED_KRPM_PER_PU * (1.0 / USER_IQ_FULL_SCALE_CURRENT_A))
Defines the default friction for the system, PU/(pu/s^2)
This value should be calculated from the friction estimated with SpinTAC Identify
Definition at line 112 of file spintac_position.h.
Referenced by ST_setupPosCtl().
#define ST_SYSTEM_INERTIA_PU (USER_SYSTEM_INERTIA * ST_SPEED_KRPM_PER_PU * (1.0 / USER_IQ_FULL_SCALE_CURRENT_A))
Defines the default inertia for the system, PU/(pu/s^2)
This value should be calculated from the inertia estimated with SpinTAC Identify
Definition at line 89 of file spintac_velocity.h.
Referenced by ST_setupVelCtl().
#define ST_SYSTEM_INERTIA_PU (USER_SYSTEM_INERTIA * ST_SPEED_KRPM_PER_PU * (1.0 / USER_IQ_FULL_SCALE_CURRENT_A))
Defines the default inertia for the system, PU/(pu/s^2)
This value should be calculated from the inertia estimated with SpinTAC Identify
Definition at line 108 of file spintac_position.h.
Referenced by ST_setupPosCtl().
#define ST_VARS_DEFAULTS
Value:
{false, \
                                  ST_VEL_ID_IDLE, \
                                  0, \
                                  0, \
                              0, \
                              0, \
                              0, \
                              true, \
                              ST_CTL_IDLE, \
                          _IQ20(USER_SYSTEM_BANDWIDTH), \
                          _IQ24(USER_MOTOR_MAX_CURRENT), \
                          -_IQ24(USER_MOTOR_MAX_CURRENT), \
                          0, \
                          ST_MOVE_IDLE, \
                          ST_MOVE_CUR_STCRV, \
                          0, \
                          0, \
                          ST_PLAN_STOP, \
                          ST_PLAN_IDLE, \
                          0, \
                          0, \
                          0, \
                          0}
GLOBAL VARIABLE INITIALIZATION.
Initalization values of SpinTAC global variables
Definition at line 114 of file spintac_velocity.h.
#define ST_VARS_DEFAULTS
Value:
{ST_CTL_IDLE, \
                              _IQ24(USER_SYSTEM_INERTIA), \
                              _IQ24(USER_SYSTEM_FRICTION), \
                          _IQ20(USER_SYSTEM_BANDWIDTH), \
                          _IQ24(USER_MOTOR_MAX_CURRENT), \
                          -_IQ24(USER_MOTOR_MAX_CURRENT), \
                          0, \
                          ST_MOVE_IDLE, \
                          ST_MOVE_CUR_STCRV, \
                          0, \
                          0, \
                          0, \
                          ST_PLAN_STOP, \
                          ST_PLAN_IDLE, \
                          0, \
                          0, \
                          0, \
                          0}
GLOBAL VARIABLE INITIALIZATION.
Initalization values of SpinTAC global variables
Definition at line 133 of file spintac_position.h.
Typedef Documentation
typedef struct _POS_Params_t POS_Params_t
Defines the position components of SpinTAC (ST)
typedef struct _ST_Obj_* ST_Handle
Handle.
Definition at line 168 of file spintac_velocity.h.
typedef struct _ST_Obj_* ST_Handle
Handle.
Definition at line 180 of file spintac_position.h.
typedef struct _ST_Obj ST_Obj
Defines the SpinTAC (ST) object.
typedef struct _ST_Obj ST_Obj
Defines the SpinTAC (ST) object.
typedef struct _ST_Vars_t ST_Vars_t
Defines the SpinTAC (ST) global variables.
typedef struct _ST_Vars_t ST_Vars_t
Defines the SpinTAC (ST) global variables.
typedef struct _VEL_Params_t VEL_Params_t
Defines the velocity components of SpinTAC (ST)
Enumeration Type Documentation
enum ST_PlanButton_e
Enumeration for the control of the velocity motion state machine (SpinTAC Velocity Plan)
Enumerator
ST_PLAN_STOP
stops the current motion sequence
ST_PLAN_START
starts the current motion sequence
ST_PLAN_PAUSE
pauses the current motion sequence
ST_PLAN_STOP
stops the current motion sequence
ST_PLAN_START
starts the current motion sequence
ST_PLAN_PAUSE
pauses the current motion sequence
Definition at line 172 of file spintac_velocity.h.
enum ST_PlanButton_e
Enumeration for the control of the position motion state machine (SpinTAC Position Plan)
Enumerator
ST_PLAN_STOP
stops the current motion sequence
ST_PLAN_START
starts the current motion sequence
ST_PLAN_PAUSE
pauses the current motion sequence
ST_PLAN_STOP
stops the current motion sequence
ST_PLAN_START
starts the current motion sequence
ST_PLAN_PAUSE
pauses the current motion sequence
Definition at line 184 of file spintac_position.h.
Function Documentation
ST_Handle ST_init (void * pMemory, const size_t numBytes) inline
Initalizes the SpinTAC (ST) object.
Definition at line 223 of file spintac_position.h.
References _POS_Params_t::conv, _POS_Params_t::ctl, _POS_Params_t::move, _POS_Params_t::plan, _ST_Obj::pos, _ST_Obj::posConvHandle, _ST_Obj::posCtlHandle, _ST_Obj::posMoveHandle, _ST_Obj::posPlanHandle, ST_initVersion(), STPOSCONV_init(), STPOSCTL_init(), STPOSMOVE_init(), STPOSPLAN_init(), _ST_Obj::version, and _ST_Obj::versionHandle.
Referenced by main().
void ST_runPosConv (ST_Handle , ENC_Handle , CTRL_Handle)
Runs SpinTAC Positon Convert.
Definition at line 615 of file proj_lab12a.c.
References CTRL_getIdq_in_addr(), ENC_getElecAngle(), _ST_Obj::posConvHandle, SLIP_setSlipVelocity(), slipHandle, STPOSCONV_getSlipVelocity(), STPOSCONV_run(), STPOSCONV_setCurrentVector(), STPOSCONV_setElecAngle_erev(), and USER_MOTOR_TYPE.
Referenced by mainISR().
void ST_runPosCtl (ST_Handle , CTRL_Handle)
Runs SpinTAC Positon Control.
Definition at line 646 of file proj_lab13a.c.
References CTRL_setIq_ref_pu(), _ST_Obj::posConvHandle, _ST_Obj::posCtlHandle, _ST_Obj::posMoveHandle, STPOSCONV_getPosition_mrev(), STPOSCTL_getTorqueReference(), STPOSCTL_run(), STPOSCTL_setAccelerationReference(), STPOSCTL_setPositionFeedback_mrev(), STPOSCTL_setPositionReference_mrev(), STPOSCTL_setVelocityReference(), STPOSMOVE_getAccelerationReference(), STPOSMOVE_getPositionReference_mrev(), and STPOSMOVE_getVelocityReference().
Referenced by mainISR().
void ST_runPosMove (ST_Handle)
Runs SpinTAC Positon Move.
Definition at line 681 of file proj_lab13b.c.
References _IQ, _IQ20, _IQ20mpy, _IQmpy, _MOTOR_Vars_t_::MaxAccel_krpmps, _MOTOR_Vars_t_::MaxDecel_krpmps, _MOTOR_Vars_t_::MaxJrk_krpmps2, _MOTOR_Vars_t_::MaxVel_krpm, _ST_Vars_t::PosMoveCurveType, _ST_Obj::posMoveHandle, _MOTOR_Vars_t_::PosStepFrac_MRev, _MOTOR_Vars_t_::PosStepInt_MRev, _MOTOR_Vars_t_::RunPositionProfile, _MOTOR_Vars_t_::SpinTAC, ST_SPEED_PU_PER_KRPM, STPOSMOVE_getStatus(), STPOSMOVE_getVelocityEnd(), STPOSMOVE_run(), STPOSMOVE_setAccelerationLimit(), STPOSMOVE_setCurveType(), STPOSMOVE_setDecelerationLimit(), STPOSMOVE_setEnable(), STPOSMOVE_setJerkLimit(), STPOSMOVE_setPositionStep_mrev(), STPOSMOVE_setProfileType(), STPOSMOVE_setVelocityEnd(), and STPOSMOVE_setVelocityLimit().
Referenced by mainISR().
void ST_runPosPlan (ST_Handle)
Runs SpinTAC Positon Plan.
Definition at line 782 of file proj_lab13c.c.
References _IQ, _IQ20, _IQ20mpy, _IQmpy, gPosPlanRunFlag, gState, gVendAvailableItem, gVendFwdButton, gVendInventory, gVendSelectButton, gVendState, _MOTOR_Vars_t_::MaxAccel_krpmps, _MOTOR_Vars_t_::MaxDecel_krpmps, _MOTOR_Vars_t_::MaxJrk_krpmps2, _MOTOR_Vars_t_::MaxVel_krpm, _ST_Obj::posMoveHandle, _ST_Obj::posPlanHandle, _ST_Vars_t::PosPlanRun, _MOTOR_Vars_t_::PosStepFrac_MRev, _MOTOR_Vars_t_::PosStepInt_MRev, _MOTOR_Vars_t_::RunPositionProfile, _MOTOR_Vars_t_::SpinTAC, ST_PLAN_PAUSE, ST_PLAN_START, ST_PLAN_STOP, ST_SPEED_KRPM_PER_PU, STPOSMOVE_getStatus(), STPOSMOVE_setEnable(), STPOSPLAN_getAccelerationLimit(), STPOSPLAN_getCurrentState(), STPOSPLAN_getDecelerationLimit(), STPOSPLAN_getErrorID(), STPOSPLAN_getFsmState(), STPOSPLAN_getJerkLimit(), STPOSPLAN_getPositionStep_mrev(), STPOSPLAN_getStatus(), STPOSPLAN_getVar(), STPOSPLAN_getVelocityLimit(), STPOSPLAN_run(), STPOSPLAN_setEnable(), STPOSPLAN_setReset(), STPOSPLAN_setVar(), VEND_Fwd, VEND_ITEM0, VEND_Item0Inv, VEND_ITEM1, VEND_Item1Inv, VEND_ITEM2, VEND_Item2Inv, VEND_ITEM3, VEND_Item3Inv, and VEND_TotalInv.
Referenced by mainISR().
void ST_runPosPlanTick (ST_Handle handle) inline
Runs the time-critical components of SpinTAC Positon Plan.
Definition at line 315 of file spintac_position.h.
References _ST_Obj::posMoveHandle, _ST_Obj::posPlanHandle, STPOSMOVE_getStatus(), STPOSPLAN_runTick(), and STPOSPLAN_setUnitProfDone().
Referenced by mainISR().
void ST_runVelCtl (ST_Handle , CTRL_Handle)
Runs SpinTAC Velocity Control.
Definition at line 569 of file proj_lab05d.c.
References _IQ, _IQmpy, CTRL_getKi(), CTRL_getKp(), CTRL_setIq_ref_pu(), CTRL_setUi(), EST_getFm_pu(), _CTRL_Obj_::estHandle, _ST_Obj::posConvHandle, _MOTOR_Vars_t_::SpinTAC, STPOSCONV_getVelocityFiltered(), STVELCTL_getTorqueReference(), STVELCTL_run(), STVELCTL_setAccelerationReference(), STVELCTL_setVelocityFeedback(), STVELCTL_setVelocityReference(), STVELMOVE_getAccelerationReference(), STVELMOVE_getVelocityReference(), TRAJ_getIntValue(), _CTRL_Obj_::trajHandle_spd, _ST_Vars_t::VelCtlEnb, _ST_Obj::velCtlHandle, and _ST_Obj::velMoveHandle.
Referenced by mainISR().
void ST_runVelId (ST_Handle , CTRL_Handle)
Runs SpinTAC Velocity Identify.
Definition at line 765 of file proj_lab05c.c.
References _IQ, _IQabs, _IQmpy, CTRL_setFlag_enableSpeedCtrl(), CTRL_setIq_ref_pu(), CTRL_setSpd_ref_krpm(), EST_getFm_pu(), EST_setFlag_enableForceAngle(), _CTRL_Obj_::estHandle, _MOTOR_Vars_t_::Flag_enableForceAngle, _ST_Obj::posConvHandle, _MOTOR_Vars_t_::SpeedRef_krpm, _MOTOR_Vars_t_::SpinTAC, ST_ID_INCOMPLETE_ERROR, ST_MIN_ID_SPEED_PU, ST_SPEED_PU_PER_KRPM, _MOTOR_Vars_t_::StopSpeedRef_krpm, STPOSCONV_getVelocityFiltered(), STVELID_getEnable(), STVELID_getErrorID(), STVELID_getStatus(), STVELID_getTorqueReference(), STVELID_run(), STVELID_setEnable(), STVELID_setGoalSpeed(), STVELID_setTorqueRampTime_sec(), STVELID_setVelocityFeedback(), _ST_Vars_t::VelIdGoalSpeed_krpm, _ST_Obj::velIdHandle, _ST_Vars_t::VelIdRun, and _ST_Vars_t::VelIdTorqueRampTime_sec.
Referenced by mainISR().
void ST_runVelMove (ST_Handle , CTRL_Handle)
Runs SpinTAC Velocity Move.
Definition at line 590 of file proj_lab06a.c.
References _IQ, _IQ20, _IQ20mpy, _IQabs, _IQmpy, EST_getState(), EST_setFlag_enableForceAngle(), _CTRL_Obj_::estHandle, _MOTOR_Vars_t_::Flag_enableForceAngle, _MOTOR_Vars_t_::MaxAccel_krpmps, _MOTOR_Vars_t_::MaxJrk_krpmps2, _MOTOR_Vars_t_::SpeedRef_krpm, _MOTOR_Vars_t_::SpinTAC, ST_MIN_ID_SPEED_PU, ST_SPEED_PU_PER_KRPM, STVELMOVE_getVelocityEnd(), STVELMOVE_getVelocityStart(), STVELMOVE_run(), STVELMOVE_setAccelerationLimit(), STVELMOVE_setCurveType(), STVELMOVE_setEnable(), STVELMOVE_setJerkLimit(), STVELMOVE_setVelocityEnd(), _ST_Vars_t::VelMoveCurveType, and _ST_Obj::velMoveHandle.
Referenced by mainISR().
void ST_runVelPlan (ST_Handle , CTRL_Handle)
Runs SpinTAC Velocity Plan.
Definition at line 663 of file proj_lab06b.c.
References _IQ, _IQ20, _IQ20mpy, _IQabs, _IQmpy, EST_getFm_pu(), _CTRL_Obj_::estHandle, GARAGE_DOOR, gConfiguredPlan, gGarageDoorButton, gGarageDoorDown, gGarageDoorUp, gGarageState, gGroceryConveyorOnOff, gGroceryConveyorProxSensor, gGroceryState, GROCERY_CONVEYOR, gSelectedPlan, gState, gTestState, gVelPanVar, gVelPlanRunFlag, gWasherState, gWaterLevel, _MOTOR_Vars_t_::MaxAccel_krpmps, _MOTOR_Vars_t_::MaxJrk_krpmps2, _MOTOR_Vars_t_::SpeedRef_krpm, _MOTOR_Vars_t_::SpinTAC, ST_MIN_ID_SPEED_PU, ST_PLAN_PAUSE, ST_PLAN_START, ST_PLAN_STOP, ST_SPEED_KRPM_PER_PU, _MOTOR_Vars_t_::StopSpeedRef_krpm, STVELPLAN_getAccelerationLimit(), STVELPLAN_getCurrentState(), STVELPLAN_getErrorID(), STVELPLAN_getFsmState(), STVELPLAN_getJerkLimit(), STVELPLAN_getStatus(), STVELPLAN_getVar(), STVELPLAN_getVelocitySetpoint(), STVELPLAN_run(), STVELPLAN_setEnable(), STVELPLAN_setReset(), STVELPLAN_setVar(), TEST_PATTERN, _ST_Obj::velPlanHandle, _ST_Vars_t::VelPlanRun, WASHER_DrainSensor, WASHER_DrainValve, WASHER_FillSensor, WASHER_FillValve, WASHER_MAX_WATER_LEVEL, and WASHER_MIN_WATER_LEVEL.
Referenced by main(), and mainISR().
void ST_runVelPlanTick (ST_Handle handle) inline
Runs the time-critical components of SpinTAC Velocity Plan.
Definition at line 296 of file spintac_velocity.h.
References STVELMOVE_getStatus(), STVELPLAN_runTick(), STVELPLAN_setUnitProfDone(), _ST_Obj::velMoveHandle, and _ST_Obj::velPlanHandle.
Referenced by mainISR().
void ST_setupPosConv (ST_Handle handle) inline
Setups SpinTAC Position Convert.
Definition at line 246 of file spintac_position.h.
References _IQ24, _ST_Obj::posConvHandle, ST_EREV_MAXIMUM, ST_MREV_ROLLOVER, ST_SAMPLE_TIME, STPOSCONV_setEnable(), STPOSCONV_setERevMaximums_erev(), STPOSCONV_setLowPassFilterTime_tick(), STPOSCONV_setMRevMaximum_mrev(), STPOSCONV_setSampleTime_sec(), STPOSCONV_setUnitConversion(), STPOSCONV_setupSlipCompensator(), USER_IQ_FULL_SCALE_FREQ_Hz, USER_MOTOR_Ls_d, USER_MOTOR_NUM_POLE_PAIRS, USER_MOTOR_Rr, and USER_MOTOR_TYPE.
Referenced by main().
void ST_setupPosCtl (ST_Handle handle) inline
Setups SpinTAC Position Control.
Definition at line 265 of file spintac_position.h.
References _IQ24, _ST_Obj::posCtlHandle, ST_MREV_ROLLOVER, ST_POS_ERROR_MAXIMUM_MREV, ST_SAMPLE_TIME, ST_SPEED_PU_PER_KRPM, ST_SYSTEM_FRICTION_PU, ST_SYSTEM_INERTIA_PU, STPOSCTL_setAxis(), STPOSCTL_setBandwidth_radps(), STPOSCTL_setEnable(), STPOSCTL_setFilterEnableFlag(), STPOSCTL_setFriction(), STPOSCTL_setInertia(), STPOSCTL_setOutputMaximums(), STPOSCTL_setPositionErrorMaximum_mrev(), STPOSCTL_setPositionRolloverMaximum_mrev(), STPOSCTL_setRampDisturbanceFlag(), STPOSCTL_setSampleTime_sec(), STPOSCTL_setUnitConversion(), STPOSCTL_setVelocityMaximum(), USER_IQ_FULL_SCALE_CURRENT_A, USER_IQ_FULL_SCALE_FREQ_Hz, USER_MOTOR_MAX_CURRENT, USER_MOTOR_MAX_SPEED_KRPM, USER_MOTOR_NUM_POLE_PAIRS, and USER_SYSTEM_BANDWIDTH.
Referenced by main().
void ST_setupPosMove (ST_Handle handle) inline
Setups SpinTAC Position Move.
Definition at line 288 of file spintac_position.h.
References _IQ20, _IQ24, _ST_Obj::posMoveHandle, ST_MREV_ROLLOVER, ST_SAMPLE_TIME, ST_SPEED_PU_PER_KRPM, STPOSMOVE_setAccelerationLimit(), STPOSMOVE_setAxis(), STPOSMOVE_setCurveType(), STPOSMOVE_setDecelerationLimit(), STPOSMOVE_setEnable(), STPOSMOVE_setJerkLimit(), STPOSMOVE_setMRevMaximum_mrev(), STPOSMOVE_setPositionStart_mrev(), STPOSMOVE_setProfileType(), STPOSMOVE_setSampleTime_sec(), STPOSMOVE_setTest(), STPOSMOVE_setUnitConversion(), STPOSMOVE_setVelocityEnd(), STPOSMOVE_setVelocityLimit(), STPOSMOVE_setVelocityStart(), USER_IQ_FULL_SCALE_FREQ_Hz, USER_MOTOR_MAX_SPEED_KRPM, and USER_MOTOR_NUM_POLE_PAIRS.
Referenced by main().
void ST_setupPosPlan (ST_Handle)
Setups SpinTAC Positon Plan.
Definition at line 684 of file proj_lab13c.c.
References _IQ, _IQ20, _IQ24, NUM_PLAN_STATES, NUM_PLAN_TRANS, NUM_VEND_ACTS, NUM_VEND_CONDS, NUM_VEND_STATES, NUM_VEND_TRANS, NUM_VEND_VARS, _ST_Obj::posPlanHandle, ST_SAMPLE_TIME, ST_SPEED_PU_PER_KRPM, STATE_A, STATE_B, STATE_C, STPOSPLAN_addCfgAct(), STPOSPLAN_addCfgCond(), STPOSPLAN_addCfgState(), STPOSPLAN_addCfgTran(), STPOSPLAN_addCfgVar(), STPOSPLAN_setCfg(), STPOSPLAN_setCfgArray(), STPOSPLAN_setCfgHaltState(), stPosPlanCfgArray, USER_MOTOR_MAX_SPEED_KRPM, VEND_Fwd, VEND_FwdPressed, VEND_INIT, VEND_INITIAL_INVENTORY, VEND_InvEmpty, VEND_ITEM0, VEND_Item0Inv, VEND_Item0InvEmpty, VEND_ITEM1, VEND_Item1Inv, VEND_Item1InvEmpty, VEND_ITEM2, VEND_Item2Inv, VEND_Item2InvEmpty, VEND_ITEM3, VEND_Item3Inv, VEND_Item3InvEmpty, and VEND_TotalInv.
Referenced by main().
void ST_setupVelCtl (ST_Handle handle) inline
Setups SpinTAC Velocity Control.
Definition at line 260 of file spintac_velocity.h.
References _IQ20, _IQ24, ST_SAMPLE_TIME, ST_SYSTEM_FRICTION_PU, ST_SYSTEM_INERTIA_PU, STVELCTL_setAxis(), STVELCTL_setBandwidth_radps(), STVELCTL_setEnable(), STVELCTL_setFriction(), STVELCTL_setInertia(), STVELCTL_setOutputMaximums(), STVELCTL_setSampleTime_sec(), USER_IQ_FULL_SCALE_CURRENT_A, USER_MOTOR_MAX_CURRENT, USER_SYSTEM_BANDWIDTH, and _ST_Obj::velCtlHandle.
Referenced by main().
void ST_setupVelId (ST_Handle handle) inline
Setups SpinTAC Velocity Identify.
Definition at line 311 of file spintac_velocity.h.
References _IQ24, ST_SAMPLE_TIME, ST_SPEED_PU_PER_KRPM, STVELID_setEnable(), STVELID_setGoalSpeed(), STVELID_setLowPassFilterTime_tick(), STVELID_setOutputMaximum(), STVELID_setSampleTime_sec(), STVELID_setTimeOut_sec(), STVELID_setTorqueRampTime_sec(), USER_IQ_FULL_SCALE_CURRENT_A, USER_MOTOR_MAX_CURRENT, USER_MOTOR_MAX_SPEED_KRPM, and _ST_Obj::velIdHandle.
Referenced by main().
void ST_setupVelMove (ST_Handle handle) inline
Setups SpinTAC Velocity Move.
Definition at line 277 of file spintac_velocity.h.
References _IQ20, _IQ24, ST_SAMPLE_TIME, STVELMOVE_setAccelerationLimit(), STVELMOVE_setAxis(), STVELMOVE_setCurveType(), STVELMOVE_setEnable(), STVELMOVE_setJerkLimit(), STVELMOVE_setSampleTime_sec(), STVELMOVE_setTest(), and _ST_Obj::velMoveHandle.
Referenced by main().
void ST_setupVelPlan (ST_Handle)
Setups SpinTAC Velocity Plan.
Definition at line 633 of file proj_lab06b.c.
References _IQ, _IQ20, _IQ24, NUM_PLAN_STATES, NUM_PLAN_TRANS, NUM_WASHER_ACTS, NUM_WASHER_CONDS, NUM_WASHER_STATES, NUM_WASHER_TRANS, NUM_WASHER_VARS, ST_SAMPLE_TIME, ST_SPEED_PU_PER_KRPM, STATE_A, STATE_B, STATE_C, STVELPLAN_addCfgAct(), STVELPLAN_addCfgCond(), STVELPLAN_addCfgState(), STVELPLAN_addCfgTran(), STVELPLAN_addCfgVar(), STVELPLAN_setCfg(), STVELPLAN_setCfgArray(), STVELPLAN_setCfgHaltState(), stVelPlanCfgArray, _ST_Obj::velPlanHandle, WASHER_AGI_CCW, WASHER_AGI_CW, WASHER_AgiDone, WASHER_AgiNotDone, WASHER_CycleCounter, WASHER_DRAIN, WASHER_DrainSensor, WASHER_DrainValve, WASHER_DRY, WASHER_FILL, WASHER_FillSensor, WASHER_FillValve, WASHER_IDLE, WASHER_WaterEmpty, and WASHER_WaterFull.
Referenced by main().