instaspin_motion: PROJ_LAB06b
PROJ_LAB06b
Modules
Project Overview
Macros
#define LED_BLINK_FREQ_Hz 5
#define ST_VELPLAN_CFG_ARRAY_DWORDS
Enumerations
enum PlanState_e { STATE_A = 0, STATE_B, STATE_C, NUM_PLAN_STATES }
enum PlanTran_e { TRAN_A_TO_B = 0, TRAN_B_TO_C, TRAN_C_TO_A, NUM_PLAN_TRANS }
Functions
void main (void)
interrupt void mainISR (void)
The main interrupt service (ISR) routine.
void updateGlobalVariables_motor (CTRL_Handle handle, ST_Handle sthandle)
Updates the global motor variables.
void updateKpKiGains (CTRL_Handle handle)
Updates Kp and Ki gains in the controller object.
void ST_setupVelPlan (ST_Handle handle)
Setups SpinTAC Velocity Plan.
void ST_runVelPlan (ST_Handle handle, CTRL_Handle ctrlHandle)
Runs SpinTAC Velocity Plan.
void ST_runVelMove (ST_Handle handle, CTRL_Handle ctrlHandle)
Runs SpinTAC Velocity Move.
void ST_runVelCtl (ST_Handle handle, CTRL_Handle ctrlHandle)
Runs SpinTAC Velocity Control.
Variables
uint_least16_t gCounter_updateGlobals = 0
bool Flag_Latch_softwareUpdate = true
CTRL_Handle ctrlHandle
HAL_Handle halHandle
USER_Params gUserParams
HAL_PwmData_t gPwmData = {_IQ(0.0), _IQ(0.0), _IQ(0.0)}
HAL_AdcData_t gAdcData
_iq gMaxCurrentSlope = _IQ(0.0)
CTRL_Obj ctrl
ST_Obj st_obj
ST_Handle stHandle
ST_PlanButton_e gVelPlanRunFlag = ST_PLAN_STOP
uint32_t stVelPlanCfgArray [ST_VELPLAN_CFG_ARRAY_DWORDS]
PlanState_e gState = STATE_A
uint16_t gLEDcnt = 0
volatile MOTOR_Vars_t gMotorVars = MOTOR_Vars_INIT
_iq gFlux_pu_to_Wb_sf
_iq gFlux_pu_to_VpHz_sf
_iq gTorque_Ls_Id_Iq_pu_to_Nm_sf
_iq gTorque_Flux_Iq_pu_to_Nm_sf
Detailed Description
Macro Definition Documentation
#define LED_BLINK_FREQ_Hz 5
Definition at line 65 of file proj_lab06b.c.
Referenced by mainISR().
#define ST_VELPLAN_CFG_ARRAY_DWORDS
Value:
((ST_VEL_PLAN_TRAN_DWORDS  * NUM_PLAN_TRANS) + \
                                                (ST_VEL_PLAN_STATE_DWORDS * NUM_PLAN_STATES))
Definition at line 119 of file proj_lab06b.c.
Enumeration Type Documentation
enum PlanState_e
Enumerator
STATE_A
STATE_B
STATE_C
NUM_PLAN_STATES
Definition at line 100 of file proj_lab06b.c.
enum PlanTran_e
Enumerator
TRAN_A_TO_B
TRAN_B_TO_C
TRAN_C_TO_A
NUM_PLAN_TRANS
Definition at line 109 of file proj_lab06b.c.
Function Documentation
void main (void)
Definition at line 153 of file proj_lab06b.c.
References _IQ, _IQmpy, CTRL_getFlag_enableUserMotorParams(), CTRL_getKi(), CTRL_getKp(), CTRL_getState(), CTRL_getVersion(), CTRL_initCtrl(), CTRL_isError(), CTRL_setFlag_enableCtrl(), CTRL_setFlag_enableDcBusComp(), CTRL_setFlag_enableOffset(), CTRL_setFlag_enablePowerWarp(), CTRL_setFlag_enableSpeedCtrl(), CTRL_setFlag_enableUserMotorParams(), CTRL_setMaxAccel_pu(), CTRL_setParams(), CTRL_setSpd_ref_krpm(), CTRL_updateState(), _MOTOR_Vars_t_::CtrlVersion, EST_getMaxCurrentSlope_pu(), EST_getState(), EST_isMotorIdentified(), EST_setFlag_enableForceAngle(), EST_setFlag_enableRsRecalc(), EST_setMaxCurrentSlope_pu(), _CTRL_Obj_::estHandle, _MOTOR_Vars_t_::Flag_enableForceAngle, _MOTOR_Vars_t_::Flag_enableOffsetcalc, _MOTOR_Vars_t_::Flag_enablePowerWarp, _MOTOR_Vars_t_::Flag_enableRsRecalc, _MOTOR_Vars_t_::Flag_enableSys, _MOTOR_Vars_t_::Flag_enableUserParams, Flag_Latch_softwareUpdate, _MOTOR_Vars_t_::Flag_MotorIdentified, _MOTOR_Vars_t_::Flag_Run_Identify, gCounter_updateGlobals, gFlux_pu_to_VpHz_sf, gFlux_pu_to_Wb_sf, gMaxCurrentSlope, gTorque_Flux_Iq_pu_to_Nm_sf, gTorque_Ls_Id_Iq_pu_to_Nm_sf, hal, HAL_disablePwm(), HAL_enableAdcInts(), HAL_enableDebugInt(), HAL_enableDrv(), HAL_enableGlobalInts(), HAL_enablePwm(), HAL_getBias(), HAL_init(), HAL_initIntVectorTable(), HAL_readDrvData(), HAL_setBias(), HAL_setParams(), HAL_setupDrvSpi(), HAL_setupFaults(), HAL_updateAdcBias(), HAL_writeDrvData(), I_A_offset, I_B_offset, _MOTOR_Vars_t_::I_bias, I_C_offset, _MOTOR_Vars_t_::Ki_Idq, _MOTOR_Vars_t_::Kp_Idq, MAX_ACCEL_KRPMPS_SF, _MOTOR_Vars_t_::MaxAccel_krpmps, memCopy(), _CTRL_Version_::minor, NUM_MAIN_TICKS_FOR_GLOBAL_VARIABLE_UPDATE, _MOTOR_Vars_t_::SpeedRef_krpm, _MOTOR_Vars_t_::SpinTAC, ST_init(), ST_setupVelCtl(), ST_setupVelMove(), ST_setupVelPlan(), stHandle, STVELCTL_getBandwidth_radps(), STVELCTL_getOutputMaximum(), STVELCTL_getOutputMinimum(), STVELCTL_setBandwidth_radps(), STVELCTL_setEnable(), STVELCTL_setOutputMaximums(), STVELMOVE_setVelocityEnd(), STVELMOVE_setVelocityStart(), updateGlobalVariables_motor(), updateKpKiGains(), USER_calcPIgains(), USER_checkForErrors(), USER_computeFlux_pu_to_VpHz_sf(), USER_computeFlux_pu_to_Wb_sf(), USER_computeTorque_Flux_Iq_pu_to_Nm_sf(), USER_computeTorque_Ls_Id_Iq_pu_to_Nm_sf(), USER_getErrorCode(), USER_IQ_FULL_SCALE_CURRENT_A, USER_setParams(), USER_softwareUpdate1p6(), _MOTOR_Vars_t_::UserErrorCode, V_A_offset, V_B_offset, _MOTOR_Vars_t_::V_bias, V_C_offset, _MATH_vec3_::value, _ST_Vars_t::VelCtlBw_radps, _ST_Obj::velCtlHandle, _ST_Vars_t::VelCtlOutputMax_A, _ST_Vars_t::VelCtlOutputMin_A, and _ST_Obj::velMoveHandle.
interrupt void mainISR (void)
The main interrupt service (ISR) routine.
Definition at line 485 of file proj_lab06b.c.
References CTRL_run(), CTRL_setup(), gLEDcnt, HAL_acqAdcInt(), HAL_readAdcData(), HAL_toggleLed, HAL_writePwmData(), ISR_TICKS_PER_SPINTAC_TICK, LED_BLINK_FREQ_Hz, ST_runVelCtl(), ST_runVelMove(), ST_runVelPlan(), ST_runVelPlanTick(), stHandle, and USER_ISR_FREQ_Hz.
void ST_runVelCtl (ST_Handle handle, CTRL_Handle ctrlHandle)
Runs SpinTAC Velocity Control.
Definition at line 757 of file proj_lab06b.c.
References CTRL_setIq_ref_pu(), EST_getFm_pu(), _CTRL_Obj_::estHandle, STVELCTL_getTorqueReference(), STVELCTL_run(), STVELCTL_setAccelerationReference(), STVELCTL_setVelocityFeedback(), STVELCTL_setVelocityReference(), STVELMOVE_getAccelerationReference(), STVELMOVE_getVelocityReference(), _ST_Obj::velCtlHandle, and _ST_Obj::velMoveHandle.
Referenced by mainISR().
void ST_runVelMove (ST_Handle handle, CTRL_Handle ctrlHandle)
Runs SpinTAC Velocity Move.
Definition at line 727 of file proj_lab06b.c.
References _IQ, _IQ20, _IQ20mpy, _IQabs, _IQmpy, EST_getState(), EST_setFlag_enableForceAngle(), _CTRL_Obj_::estHandle, _MOTOR_Vars_t_::Flag_enableForceAngle, _MOTOR_Vars_t_::MaxAccel_krpmps, _MOTOR_Vars_t_::MaxJrk_krpmps2, _MOTOR_Vars_t_::SpeedRef_krpm, _MOTOR_Vars_t_::SpinTAC, ST_MIN_ID_SPEED_PU, ST_SPEED_PU_PER_KRPM, STVELMOVE_getVelocityEnd(), STVELMOVE_getVelocityStart(), STVELMOVE_run(), STVELMOVE_setAccelerationLimit(), STVELMOVE_setCurveType(), STVELMOVE_setEnable(), STVELMOVE_setJerkLimit(), STVELMOVE_setVelocityEnd(), _ST_Vars_t::VelMoveCurveType, and _ST_Obj::velMoveHandle.
Referenced by mainISR().
void ST_runVelPlan (ST_Handle handle, CTRL_Handle ctrlHandle)
Runs SpinTAC Velocity Plan.
Definition at line 663 of file proj_lab06b.c.
Referenced by mainISR().
void ST_setupVelPlan (ST_Handle handle)
Setups SpinTAC Velocity Plan.
Definition at line 633 of file proj_lab06b.c.
Referenced by main().
void updateGlobalVariables_motor (CTRL_Handle handle, ST_Handle sthandle)
Updates the global motor variables.
Definition at line 532 of file proj_lab06b.c.
References _IQ, _IQmpy, CTRL_getState(), _MOTOR_Vars_t_::CtrlState, _HAL_AdcData_t_::dcBus, EST_get_pu_to_krpm_sf(), EST_getFlux_VpHz(), EST_getIdRated(), EST_getLs_d_H(), EST_getLs_q_H(), EST_getRr_Ohm(), EST_getRs_Ohm(), EST_getSpeed_krpm(), EST_getState(), _CTRL_Obj_::estHandle, _MOTOR_Vars_t_::EstState, _MOTOR_Vars_t_::Flux_VpHz, _MOTOR_Vars_t_::Flux_Wb, _ST_Vars_t::FrictionEstimate_Aperkrpm, gFlux_pu_to_Wb_sf, gTorque_Flux_Iq_pu_to_Nm_sf, gTorque_Ls_Id_Iq_pu_to_Nm_sf, _ST_Vars_t::InertiaEstimate_Aperkrpm, _MOTOR_Vars_t_::IqRef_A, _MOTOR_Vars_t_::Lsd_H, _MOTOR_Vars_t_::Lsq_H, _MOTOR_Vars_t_::MagnCurr_A, _MOTOR_Vars_t_::Rr_Ohm, _MOTOR_Vars_t_::Rs_Ohm, _MOTOR_Vars_t_::Speed_krpm, _MOTOR_Vars_t_::SpeedTraj_krpm, _MOTOR_Vars_t_::SpinTAC, ST_SPEED_PU_PER_KRPM, STVELCTL_getErrorID(), STVELCTL_getFriction(), STVELCTL_getInertia(), STVELCTL_getStatus(), STVELCTL_getTorqueReference(), STVELMOVE_getErrorID(), STVELMOVE_getProfileTime_tick(), STVELMOVE_getStatus(), STVELMOVE_getVelocityReference(), STVELPLAN_getCfgError(), STVELPLAN_getStatus(), _MOTOR_Vars_t_::Torque_Nm, USER_computeFlux(), USER_computeTorque_Nm(), USER_IQ_FULL_SCALE_CURRENT_A, USER_IQ_FULL_SCALE_VOLTAGE_V, _MOTOR_Vars_t_::VdcBus_kV, _ST_Vars_t::VelCtlErrorID, _ST_Obj::velCtlHandle, _ST_Vars_t::VelCtlStatus, _ST_Vars_t::VelMoveErrorID, _ST_Obj::velMoveHandle, _ST_Vars_t::VelMoveStatus, _ST_Vars_t::VelMoveTime_ticks, _ST_Vars_t::VelPlanCfgErrorCode, _ST_Vars_t::VelPlanCfgErrorIdx, _ST_Vars_t::VelPlanErrorID, _ST_Obj::velPlanHandle, and _ST_Vars_t::VelPlanStatus.
Referenced by main().
void updateKpKiGains (CTRL_Handle handle)
Updates Kp and Ki gains in the controller object.
Definition at line 614 of file proj_lab06b.c.
References CTRL_setKi(), CTRL_setKp(), _MOTOR_Vars_t_::CtrlState, Flag_Latch_softwareUpdate, _MOTOR_Vars_t_::Flag_MotorIdentified, _MOTOR_Vars_t_::Ki_Idq, _MOTOR_Vars_t_::Ki_spd, _MOTOR_Vars_t_::Kp_Idq, and _MOTOR_Vars_t_::Kp_spd.
Referenced by main().
Variable Documentation
CTRL_Obj ctrl
Definition at line 90 of file proj_lab06b.c.
CTRL_Handle ctrlHandle
Definition at line 75 of file proj_lab06b.c.
bool Flag_Latch_softwareUpdate = true
Definition at line 73 of file proj_lab06b.c.
Referenced by main(), and updateKpKiGains().
HAL_AdcData_t gAdcData
Definition at line 83 of file proj_lab06b.c.
uint_least16_t gCounter_updateGlobals = 0
Definition at line 71 of file proj_lab06b.c.
Referenced by main().
_iq gFlux_pu_to_VpHz_sf
Definition at line 144 of file proj_lab06b.c.
Referenced by main().
_iq gFlux_pu_to_Wb_sf
Definition at line 142 of file proj_lab06b.c.
Referenced by main(), and updateGlobalVariables_motor().
uint16_t gLEDcnt = 0
Definition at line 127 of file proj_lab06b.c.
Referenced by mainISR().
_iq gMaxCurrentSlope = _IQ(0.0)
Definition at line 85 of file proj_lab06b.c.
Referenced by main().
volatile MOTOR_Vars_t gMotorVars = MOTOR_Vars_INIT
Definition at line 129 of file proj_lab06b.c.
HAL_PwmData_t gPwmData = {_IQ(0.0), _IQ(0.0), _IQ(0.0)}
Definition at line 81 of file proj_lab06b.c.
PlanState_e gState = STATE_A
Definition at line 125 of file proj_lab06b.c.
Referenced by ST_runVelPlan().
_iq gTorque_Flux_Iq_pu_to_Nm_sf
Definition at line 148 of file proj_lab06b.c.
Referenced by main(), and updateGlobalVariables_motor().
_iq gTorque_Ls_Id_Iq_pu_to_Nm_sf
Definition at line 146 of file proj_lab06b.c.
Referenced by main(), and updateGlobalVariables_motor().
USER_Params gUserParams
Definition at line 79 of file proj_lab06b.c.
ST_PlanButton_e gVelPlanRunFlag = ST_PLAN_STOP
Definition at line 97 of file proj_lab06b.c.
Referenced by ST_runVelPlan().
HAL_Handle halHandle
Definition at line 77 of file proj_lab06b.c.
ST_Obj st_obj
Definition at line 93 of file proj_lab06b.c.
ST_Handle stHandle
Definition at line 94 of file proj_lab06b.c.
Referenced by main(), and mainISR().
uint32_t stVelPlanCfgArray[ST_VELPLAN_CFG_ARRAY_DWORDS]
Definition at line 123 of file proj_lab06b.c.
Referenced by ST_setupVelPlan().