instaspin_motion: PROJ_LAB05c
PROJ_LAB05c
Modules
Project Overview
Macros
#define LED_BLINK_FREQ_Hz 5
Functions
void main (void)
interrupt void mainISR (void)
The main interrupt service (ISR) routine.
void updateGlobalVariables_motor (CTRL_Handle handle, ST_Handle sthandle)
Updates the global motor variables.
void updateKpKiGains (CTRL_Handle handle)
Updates Kp and Ki gains in the controller object.
void CTRL_resetLs_qFmt (CTRL_Handle handle, const uint_least8_t Ls_qFmt)
Reset Ls Q format to a higher value when Ls identification starts.
void recalcKpKiPmsm (CTRL_Handle handle)
Recalculate Kp and Ki gains to fix the R/L limitation of 2000.0 and Kp limitation of 0.11.
void CTRL_calcMax_Ls_qFmt (CTRL_Handle handle, uint_least8_t *pLs_qFmt)
Calculates the maximum qFmt value for Ls identification, to get a more accurate Ls per unit.
void recalcKpKi (CTRL_Handle handle)
Recalculate Kp and Ki gains to fix the R/L limitation of 2000.0 and Kp limitation of 0.11.
void setFeLimitZero (CTRL_Handle handle)
Set electrical frequency limit to zero while identifying an induction motor.
void acim_Dir_qFmtCalc (CTRL_Handle handle)
Calculates Dir_qFmt for ACIM.
void ST_runVelId (ST_Handle handle, CTRL_Handle ctrlHandle)
Runs SpinTAC Velocity Identify.
Variables
uint_least16_t gCounter_updateGlobals = 0
bool Flag_Latch_softwareUpdate = true
CTRL_Handle ctrlHandle
HAL_Handle halHandle
USER_Params gUserParams
HAL_PwmData_t gPwmData = {_IQ(0.0), _IQ(0.0), _IQ(0.0)}
HAL_AdcData_t gAdcData
_iq gMaxCurrentSlope = _IQ(0.0)
CTRL_Obj ctrl
ST_Obj st_obj
ST_Handle stHandle
uint16_t gLEDcnt = 0
volatile MOTOR_Vars_t gMotorVars = MOTOR_Vars_INIT
_iq gLs_pu = _IQ30(0.0)
uint_least8_t gLs_qFmt = 0
uint_least8_t gMax_Ls_qFmt = 0
_iq gFlux_pu_to_Wb_sf
_iq gFlux_pu_to_VpHz_sf
_iq gTorque_Ls_Id_Iq_pu_to_Nm_sf
_iq gTorque_Flux_Iq_pu_to_Nm_sf
Detailed Description
Macro Definition Documentation
#define LED_BLINK_FREQ_Hz 5
Definition at line 65 of file proj_lab05c.c.
Referenced by mainISR().
Function Documentation
void acim_Dir_qFmtCalc (CTRL_Handle handle)
Calculates Dir_qFmt for ACIM.
Definition at line 751 of file proj_lab05c.c.
References EST_computeDirection_qFmt(), EST_getState(), EST_setDir_qFmt(), and _CTRL_Obj_::estHandle.
Referenced by main().
void CTRL_calcMax_Ls_qFmt (CTRL_Handle handle, uint_least8_t * pLs_qFmt)
Calculates the maximum qFmt value for Ls identification, to get a more accurate Ls per unit.
Definition at line 671 of file proj_lab05c.c.
References _IQ30toF(), CTRL_getLhf(), EST_getLs_coarse_max_pu(), EST_getState(), EST_isMotorIdentified(), _CTRL_Obj_::estHandle, USER_IQ_FULL_SCALE_CURRENT_A, USER_IQ_FULL_SCALE_VOLTAGE_V, and USER_VOLTAGE_FILTER_POLE_rps.
Referenced by main().
void CTRL_resetLs_qFmt (CTRL_Handle handle, const uint_least8_t Ls_qFmt)
Reset Ls Q format to a higher value when Ls identification starts.
Definition at line 593 of file proj_lab05c.c.
References _IQ30, EST_getLs_d_pu(), EST_getState(), EST_setLs_qFmt(), and _CTRL_Obj_::estHandle.
Referenced by mainISR().
void main (void)
Definition at line 125 of file proj_lab05c.c.
References _IQ, _IQmpy, acim_Dir_qFmtCalc(), CTRL_calcMax_Ls_qFmt(), CTRL_getFlag_enableUserMotorParams(), CTRL_getKi(), CTRL_getKp(), CTRL_getMotorType(), CTRL_getState(), CTRL_getVersion(), CTRL_initCtrl(), CTRL_isError(), CTRL_setFlag_enableCtrl(), CTRL_setFlag_enableDcBusComp(), CTRL_setFlag_enableOffset(), CTRL_setFlag_enablePowerWarp(), CTRL_setFlag_enableSpeedCtrl(), CTRL_setFlag_enableUserMotorParams(), CTRL_setMaxAccel_pu(), CTRL_setParams(), CTRL_setSpd_ref_krpm(), CTRL_updateState(), _MOTOR_Vars_t_::CtrlVersion, EST_getLs_d_pu(), EST_getLs_qFmt(), EST_getMaxCurrentSlope_pu(), EST_getState(), EST_isMotorIdentified(), EST_setFlag_enableForceAngle(), EST_setFlag_enableRsRecalc(), EST_setMaxCurrentSlope_pu(), _CTRL_Obj_::estHandle, _MOTOR_Vars_t_::Flag_enableForceAngle, _MOTOR_Vars_t_::Flag_enableOffsetcalc, _MOTOR_Vars_t_::Flag_enablePowerWarp, _MOTOR_Vars_t_::Flag_enableRsRecalc, _MOTOR_Vars_t_::Flag_enableSys, _MOTOR_Vars_t_::Flag_enableUserParams, Flag_Latch_softwareUpdate, _MOTOR_Vars_t_::Flag_MotorIdentified, _MOTOR_Vars_t_::Flag_Run_Identify, gCounter_updateGlobals, gFlux_pu_to_VpHz_sf, gFlux_pu_to_Wb_sf, gLs_pu, gLs_qFmt, gMax_Ls_qFmt, gMaxCurrentSlope, gTorque_Flux_Iq_pu_to_Nm_sf, gTorque_Ls_Id_Iq_pu_to_Nm_sf, hal, HAL_disablePwm(), HAL_enableAdcInts(), HAL_enableDebugInt(), HAL_enableDrv(), HAL_enableGlobalInts(), HAL_enablePwm(), HAL_getBias(), HAL_init(), HAL_initIntVectorTable(), HAL_readDrvData(), HAL_setParams(), HAL_setupDrvSpi(), HAL_setupFaults(), HAL_updateAdcBias(), HAL_writeDrvData(), _MOTOR_Vars_t_::I_bias, _MOTOR_Vars_t_::Ki_Idq, _MOTOR_Vars_t_::Ki_spd, _MOTOR_Vars_t_::Kp_Idq, _MOTOR_Vars_t_::Kp_spd, MAX_ACCEL_KRPMPS_SF, _MOTOR_Vars_t_::MaxAccel_krpmps, memCopy(), _CTRL_Version_::minor, NUM_MAIN_TICKS_FOR_GLOBAL_VARIABLE_UPDATE, recalcKpKi(), recalcKpKiPmsm(), setFeLimitZero(), _MOTOR_Vars_t_::SpeedRef_krpm, _MOTOR_Vars_t_::SpinTAC, ST_init(), ST_setupVelId(), ST_SPEED_KRPM_PER_PU, stHandle, STVELID_getGoalSpeed(), STVELID_getTorqueRampTime_sec(), updateGlobalVariables_motor(), updateKpKiGains(), USER_calcPIgains(), USER_checkForErrors(), USER_computeFlux_pu_to_VpHz_sf(), USER_computeFlux_pu_to_Wb_sf(), USER_computeTorque_Flux_Iq_pu_to_Nm_sf(), USER_computeTorque_Ls_Id_Iq_pu_to_Nm_sf(), USER_getErrorCode(), USER_setParams(), USER_softwareUpdate1p6(), _MOTOR_Vars_t_::UserErrorCode, _MOTOR_Vars_t_::V_bias, _MATH_vec3_::value, _ST_Vars_t::VelIdGoalSpeed_krpm, _ST_Obj::velIdHandle, and _ST_Vars_t::VelIdTorqueRampTime_sec.
interrupt void mainISR (void)
The main interrupt service (ISR) routine.
Definition at line 455 of file proj_lab05c.c.
References CTRL_getMotorType(), CTRL_resetLs_qFmt(), CTRL_run(), CTRL_setup(), gLEDcnt, gMax_Ls_qFmt, HAL_acqAdcInt(), HAL_readAdcData(), HAL_toggleLed, HAL_writePwmData(), ISR_TICKS_PER_SPINTAC_TICK, LED_BLINK_FREQ_Hz, ST_runVelId(), stHandle, and USER_ISR_FREQ_Hz.
void recalcKpKi (CTRL_Handle handle)
Recalculate Kp and Ki gains to fix the R/L limitation of 2000.0 and Kp limitation of 0.11.
Definition at line 689 of file proj_lab05c.c.
References _IQ, CTRL_getLhf(), CTRL_getRhf(), CTRL_setKi(), CTRL_setKp(), CTRL_setRoverL(), EST_getState(), EST_isMotorIdentified(), _CTRL_Obj_::estHandle, PID_setKi(), _CTRL_Obj_::pidHandle_Id, _CTRL_Obj_::pidHandle_Iq, USER_CTRL_PERIOD_sec, USER_IQ_FULL_SCALE_CURRENT_A, and USER_IQ_FULL_SCALE_VOLTAGE_V.
Referenced by main().
void recalcKpKiPmsm (CTRL_Handle handle)
Recalculate Kp and Ki gains to fix the R/L limitation of 2000.0 and Kp limitation of 0.11.
as well as recalculates gains based on estimator state to allow low inductance pmsm to id
Definition at line 616 of file proj_lab05c.c.
References _IQ, CTRL_getLhf(), CTRL_getRhf(), CTRL_setKi(), CTRL_setKp(), CTRL_setRoverL(), EST_getState(), EST_isMotorIdentified(), _CTRL_Obj_::estHandle, PID_setKi(), PID_setKp(), _CTRL_Obj_::pidHandle_Id, _CTRL_Obj_::pidHandle_Iq, _CTRL_Obj_::pidHandle_spd, TRAJ_setTargetValue(), _CTRL_Obj_::trajHandle_spdMax, USER_CTRL_PERIOD_sec, USER_IQ_FULL_SCALE_CURRENT_A, USER_IQ_FULL_SCALE_FREQ_Hz, USER_IQ_FULL_SCALE_VOLTAGE_V, USER_MOTOR_MAX_CURRENT, and USER_MOTOR_RES_EST_CURRENT.
Referenced by main().
void setFeLimitZero (CTRL_Handle handle)
Set electrical frequency limit to zero while identifying an induction motor.
Definition at line 722 of file proj_lab05c.c.
References _IQ30, CTRL_getMotorType(), EST_getState(), EST_isMotorIdentified(), EST_setFe_neg_max_pu(), EST_setFe_pos_min_pu(), _CTRL_Obj_::estHandle, and USER_ZEROSPEEDLIMIT.
Referenced by main().
void ST_runVelId (ST_Handle handle, CTRL_Handle ctrlHandle)
Runs SpinTAC Velocity Identify.
Definition at line 765 of file proj_lab05c.c.
Referenced by mainISR().
void updateGlobalVariables_motor (CTRL_Handle handle, ST_Handle sthandle)
Updates the global motor variables.
Definition at line 505 of file proj_lab05c.c.
References _IQ, _IQmpy, CTRL_getSpd_int_ref_pu(), CTRL_getSpd_out_pu(), CTRL_getState(), _MOTOR_Vars_t_::CtrlState, _HAL_AdcData_t_::dcBus, EST_get_pu_to_krpm_sf(), EST_getFlux_VpHz(), EST_getIdRated(), EST_getLs_d_H(), EST_getLs_q_H(), EST_getRr_Ohm(), EST_getRs_Ohm(), EST_getSpeed_krpm(), EST_getState(), _CTRL_Obj_::estHandle, _MOTOR_Vars_t_::EstState, _MOTOR_Vars_t_::Flux_VpHz, _MOTOR_Vars_t_::Flux_Wb, _ST_Vars_t::FrictionEstimate_Aperkrpm, gFlux_pu_to_Wb_sf, gTorque_Flux_Iq_pu_to_Nm_sf, gTorque_Ls_Id_Iq_pu_to_Nm_sf, _ST_Vars_t::InertiaEstimate_Aperkrpm, _MOTOR_Vars_t_::IqRef_A, _MOTOR_Vars_t_::Lsd_H, _MOTOR_Vars_t_::Lsq_H, _MOTOR_Vars_t_::MagnCurr_A, _MOTOR_Vars_t_::Rr_Ohm, _MOTOR_Vars_t_::Rs_Ohm, _MOTOR_Vars_t_::Speed_krpm, _MOTOR_Vars_t_::SpeedTraj_krpm, _MOTOR_Vars_t_::SpinTAC, ST_SPEED_PU_PER_KRPM, STVELID_getErrorID(), STVELID_getFrictionEstimate(), STVELID_getInertiaEstimate(), STVELID_getStatus(), STVELID_getTorqueReference(), _MOTOR_Vars_t_::Torque_Nm, USER_computeFlux(), USER_computeTorque_Nm(), USER_IQ_FULL_SCALE_CURRENT_A, USER_IQ_FULL_SCALE_VOLTAGE_V, _MOTOR_Vars_t_::VdcBus_kV, _ST_Vars_t::VelIdErrorID, _ST_Obj::velIdHandle, _ST_Vars_t::VelIdRun, and _ST_Vars_t::VelIdStatus.
Referenced by main().
void updateKpKiGains (CTRL_Handle handle)
Updates Kp and Ki gains in the controller object.
Definition at line 574 of file proj_lab05c.c.
References CTRL_setKi(), CTRL_setKp(), _MOTOR_Vars_t_::CtrlState, Flag_Latch_softwareUpdate, _MOTOR_Vars_t_::Flag_MotorIdentified, _MOTOR_Vars_t_::Ki_Idq, _MOTOR_Vars_t_::Ki_spd, _MOTOR_Vars_t_::Kp_Idq, and _MOTOR_Vars_t_::Kp_spd.
Referenced by main().
Variable Documentation
CTRL_Obj ctrl
Definition at line 90 of file proj_lab05c.c.
CTRL_Handle ctrlHandle
Definition at line 75 of file proj_lab05c.c.
bool Flag_Latch_softwareUpdate = true
Definition at line 73 of file proj_lab05c.c.
Referenced by main(), and updateKpKiGains().
HAL_AdcData_t gAdcData
Definition at line 83 of file proj_lab05c.c.
uint_least16_t gCounter_updateGlobals = 0
Definition at line 71 of file proj_lab05c.c.
Referenced by main().
_iq gFlux_pu_to_VpHz_sf
Definition at line 116 of file proj_lab05c.c.
Referenced by main().
_iq gFlux_pu_to_Wb_sf
Definition at line 114 of file proj_lab05c.c.
Referenced by main(), and updateGlobalVariables_motor().
uint16_t gLEDcnt = 0
Definition at line 96 of file proj_lab05c.c.
Referenced by mainISR().
_iq gLs_pu = _IQ30(0.0)
Definition at line 105 of file proj_lab05c.c.
Referenced by main().
uint_least8_t gLs_qFmt = 0
Definition at line 106 of file proj_lab05c.c.
Referenced by main().
uint_least8_t gMax_Ls_qFmt = 0
Definition at line 107 of file proj_lab05c.c.
Referenced by main(), and mainISR().
_iq gMaxCurrentSlope = _IQ(0.0)
Definition at line 85 of file proj_lab05c.c.
Referenced by main().
volatile MOTOR_Vars_t gMotorVars = MOTOR_Vars_INIT
Definition at line 98 of file proj_lab05c.c.
HAL_PwmData_t gPwmData = {_IQ(0.0), _IQ(0.0), _IQ(0.0)}
Definition at line 81 of file proj_lab05c.c.
_iq gTorque_Flux_Iq_pu_to_Nm_sf
Definition at line 120 of file proj_lab05c.c.
Referenced by main(), and updateGlobalVariables_motor().
_iq gTorque_Ls_Id_Iq_pu_to_Nm_sf
Definition at line 118 of file proj_lab05c.c.
Referenced by main(), and updateGlobalVariables_motor().
USER_Params gUserParams
Definition at line 79 of file proj_lab05c.c.
HAL_Handle halHandle
Definition at line 77 of file proj_lab05c.c.
ST_Obj st_obj
Definition at line 93 of file proj_lab05c.c.
ST_Handle stHandle
Definition at line 94 of file proj_lab05c.c.
Referenced by main(), and mainISR().